force-app/main/default/objects/Author__c/Author__c.object-meta.xml
<CustomObject>
    <label>Author</label>
    <nameField>
        <displayFormat>AP-{0000}</displayFormat>
        <label>Author Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Authors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Book__c/Book__c.object-meta.xml
<CustomObject>
    <label>Book</label>
    <nameField>
        <label>Book Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Books</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Book__c/fields/Author__c.field-meta.xml
<CustomField>
    <fullName>Author__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Author</label>
    <referenceTo>Author__c</referenceTo>
    <relationshipLabel>Books</relationshipLabel>
    <relationshipName>Books</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Book__c/fields/Publisher__c.field-meta.xml
<CustomField>
    <fullName>Publisher__c</fullName>
    <label>Publisher</label>
    <referenceTo>Publisher__c</referenceTo>
    <relationshipLabel>Books</relationshipLabel>
    <relationshipName>Books</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Book_Review__c/Book_Review__c.object-meta.xml
<CustomObject>
    <label>Book Review</label>
    <nameField>
        <label>Subject</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Book Reviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Book_Review__c/fields/Book__c.field-meta.xml
<CustomField>
    <fullName>Book__c</fullName>
    <description>Master - Detail relationship with associated Book</description>
    <inlineHelpText>Master - Detail relationship with associated Book</inlineHelpText>
    <label>Book</label>
    <referenceTo>Book__c</referenceTo>
    <relationshipLabel>Book Reviews</relationshipLabel>
    <relationshipName>Book_Reviews</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Publisher__c/Publisher__c.object-meta.xml
<CustomObject>
    <label>Publisher</label>
    <nameField>
        <label>Publisher Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Publishers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/test/default/classes/unit/BookReviewValidationServiceTest.cls
/*
* This class is used for testing book review validation service
* There will be 1 positive, 1 negative and 1 mockerexecutioncount tests
*/
@isTest
public with sharing class BookReviewValidationServiceTest {
    @isTest
    public static void validateReview_willAddError_ifSameBookReviewsAreCreated() {
        //Create data for test
        TestFactory testFactory = new TestFactory();
        Map<String, String> publisherDetails = new Map<String, String>();
        publisherDetails.put('name', 'publisher');
        publisherDetails.put('email', 'publisher@gmail.com');
        publisherDetails.put('phone', '1241353');
        Publisher__c publisherForTest = testFactory.createPublisher(publisherDetails, false, true);

        Map<String, String> authorDetails = new Map<String, String>();
        authorDetails.put('firstName', 'Author');
        authorDetails.put('lastName', 'Author');
        Author__c authorForTest = testFactory.createAuthor(authorDetails, false, true);

        Map<String, String> bookDetails = new Map<String, String>();
        bookDetails.put('name', 'book');
        bookDetails.put('description', 'bookdesc');
        bookDetails.put('ISBN', '214215425');
        bookDetails.put('language', 'english');
        bookDetails.put('categories', 'fantasy');
        Book__c bookForTest = testFactory.createBook(publisherForTest.Id, authorForTest.Id, bookDetails, false, true);

        Map<String, String> bookReviewDetails = new Map<String, String>();
        bookReviewDetails.put('name', 'Good Book');
        bookReviewDetails.put('rating', '4');
        Book_Review__c bookReviewForInsert = testFactory.createBookReview(bookForTest.Id, bookReviewDetails, false, true);

        Test.startTest();
        BookReviewValidationService service = new BookReviewValidationService();
        service.validateReview(new List<Book_Review__c>{bookReviewForInsert, bookReviewForInsert});
        Test.stopTest();

        System.assert(bookReviewForInsert.getErrors().size() == 1);
    }

    @isTest
    public static void validateReview_willNotAddError_ifSameBookReviewDoesentExist() {
        //Create data for test
        TestFactory testFactory = new TestFactory();
        Map<String, String> publisherDetails = new Map<String, String>();
        publisherDetails.put('name', 'publisher');
        publisherDetails.put('email', 'publisher@gmail.com');
        publisherDetails.put('phone', '1241353');
        Publisher__c publisherForTest = testFactory.createPublisher(publisherDetails, false, true);

        Map<String, String> authorDetails = new Map<String, String>();
        authorDetails.put('firstName', 'Author');
        authorDetails.put('lastName', 'Author');
        Author__c authorForTest = testFactory.createAuthor(authorDetails, false, true);

        Map<String, String> bookDetails = new Map<String, String>();
        bookDetails.put('name', 'book');
        bookDetails.put('description', 'bookdesc');
        bookDetails.put('ISBN', '214215425');
        bookDetails.put('language', 'english');
        bookDetails.put('categories', 'fantasy');
        Book__c bookForTest = testFactory.createBook(publisherForTest.Id, authorForTest.Id, bookDetails, false, true);

        Map<String, String> bookReviewDetails = new Map<String, String>();
        bookReviewDetails.put('name', 'Good Book');
        bookReviewDetails.put('rating', '4');
        Book_Review__c bookReviewForInsert = testFactory.createBookReview(bookForTest.Id, bookReviewDetails, false, true);

        Mocker BookReviewSelectorMock = new Mocker(BookReviewSelector.class)
        .setBehavior('getList', new List<Book_Review__c>());

        ObjectFactory.mocks.put(
            BookReviewSelector.class.getName(),
            (BookReviewSelector) BookReviewSelectorMock.getMock()
        );

        Test.startTest();
        BookReviewValidationService service = new BookReviewValidationService();
        service.validateReview(new List<Book_Review__c>{bookReviewForInsert});
        Test.stopTest();

        System.assert(bookReviewForInsert.getErrors().size() == 0);
    }

    @isTest
    public static void validateReview_willUseCorrectSelector() {
        //Create data for test
        TestFactory testFactory = new TestFactory();
        Map<String, String> publisherDetails = new Map<String, String>();
        publisherDetails.put('name', 'publisher');
        publisherDetails.put('email', 'publisher@gmail.com');
        publisherDetails.put('phone', '1241353');
        Publisher__c publisherForTest = testFactory.createPublisher(publisherDetails, false, true);

        Map<String, String> authorDetails = new Map<String, String>();
        authorDetails.put('firstName', 'Author');
        authorDetails.put('lastName', 'Author');
        Author__c authorForTest = testFactory.createAuthor(authorDetails, false, true);

        Map<String, String> bookDetails = new Map<String, String>();
        bookDetails.put('name', 'book');
        bookDetails.put('description', 'bookdesc');
        bookDetails.put('ISBN', '214215425');
        bookDetails.put('language', 'english');
        bookDetails.put('categories', 'fantasy');
        Book__c bookForTest = testFactory.createBook(publisherForTest.Id, authorForTest.Id, bookDetails, false, true);

        Map<String, String> bookReviewDetails = new Map<String, String>();
        bookReviewDetails.put('name', 'Good Book');
        bookReviewDetails.put('rating', '4');
        Book_Review__c bookReviewForInsert = testFactory.createBookReview(bookForTest.Id, bookReviewDetails, false, true);

        Mocker BookReviewSelectorMock = new Mocker(BookReviewSelector.class)
        .setBehavior('getList', new List<Book_Review__c>());

        ObjectFactory.mocks.put(
            BookReviewSelector.class.getName(),
            (BookReviewSelector) BookReviewSelectorMock.getMock()
        );

        Test.startTest();
        BookReviewValidationService service = new BookReviewValidationService();
        service.validateReview(new List<Book_Review__c>{bookReviewForInsert});
        Test.stopTest();

        BookReviewSelectorMock.assertMethodExecutionCount('getList', 1);
    }
}