force-app/main/default/objects/Author__c/Author__c.object-meta.xml
<CustomObject>
    <label>Author</label>
    <nameField>
        <displayFormat>AP-{0000}</displayFormat>
        <label>Author Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Authors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Author_Publisher__c/Author_Publisher__c.object-meta.xml
<CustomObject>
    <label>Author_Publisher</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Author_Publisher Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Author_Publishers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Author_Publisher__c/fields/Author__c.field-meta.xml
<CustomField>
    <fullName>Author__c</fullName>
    <label>Author</label>
    <referenceTo>Author__c</referenceTo>
    <relationshipLabel>Author_Publishers</relationshipLabel>
    <relationshipName>Author_Publishers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Author_Publisher__c/fields/Publisher__c.field-meta.xml
<CustomField>
    <fullName>Publisher__c</fullName>
    <label>Publisher</label>
    <referenceTo>Publisher__c</referenceTo>
    <relationshipLabel>Author_Publishers</relationshipLabel>
    <relationshipName>Author_Publishers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Book__c/Book__c.object-meta.xml
<CustomObject>
    <label>Book</label>
    <nameField>
        <label>Book Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Books</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Book__c/fields/Author__c.field-meta.xml
<CustomField>
    <fullName>Author__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Author</label>
    <referenceTo>Author__c</referenceTo>
    <relationshipLabel>Books</relationshipLabel>
    <relationshipName>Books</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Book__c/fields/ISBN__c.field-meta.xml
<CustomField>
    <fullName>ISBN__c</fullName>
    <description>Unique book identifier</description>
    <inlineHelpText>Unique book identifier</inlineHelpText>
    <label>ISBN</label>
    <length>13</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Book__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Price</label>
    <precision>17</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Book__c/fields/Publisher__c.field-meta.xml
<CustomField>
    <fullName>Publisher__c</fullName>
    <label>Publisher</label>
    <referenceTo>Publisher__c</referenceTo>
    <relationshipLabel>Books</relationshipLabel>
    <relationshipName>Books</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Book_Reservation__c/Book_Reservation__c.object-meta.xml
<CustomObject>
    <label>Book Reservation</label>
    <nameField>
        <displayFormat>RES-{0000}</displayFormat>
        <label>Book Reservation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Book Reservations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Book_Reservation__c/fields/Book__c.field-meta.xml
<CustomField>
    <fullName>Book__c</fullName>
    <label>Book</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>You must select a Paper Book!</errorMessage>
        <filterItems>
            <field>Book__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Paper Book</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Book__c</referenceTo>
    <relationshipLabel>Book Reservations</relationshipLabel>
    <relationshipName>Book_Reservations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Book_Reservation__c/fields/Bookstore__c.field-meta.xml
<CustomField>
    <fullName>Bookstore__c</fullName>
    <label>Bookstore</label>
    <referenceTo>Bookstore__c</referenceTo>
    <relationshipLabel>Book Reservations</relationshipLabel>
    <relationshipName>Book_Reservations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Bookstore__c/Bookstore__c.object-meta.xml
<CustomObject>
    <label>Bookstore</label>
    <nameField>
        <label>Bookstore Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookstores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Bookstore_Book__c/Bookstore_Book__c.object-meta.xml
<CustomObject>
    <label>Bookstore_Book</label>
    <nameField>
        <label>Bookstore_Book Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookstore_Books</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bookstore_Book__c/fields/Book__c.field-meta.xml
<CustomField>
    <fullName>Book__c</fullName>
    <label>Book</label>
    <referenceTo>Book__c</referenceTo>
    <relationshipLabel>Bookstore Books</relationshipLabel>
    <relationshipName>Bookstore_Books</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Bookstore_Book__c/fields/Bookstore__c.field-meta.xml
<CustomField>
    <fullName>Bookstore__c</fullName>
    <label>Bookstore</label>
    <referenceTo>Bookstore__c</referenceTo>
    <relationshipLabel>Bookstore Books</relationshipLabel>
    <relationshipName>Bookstore_Books</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Bookstore_Book__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <description>Number of copies of a single book title.</description>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Bookstore_Publisher__c/Bookstore_Publisher__c.object-meta.xml
<CustomObject>
    <label>Bookstore_Publisher</label>
    <nameField>
        <displayFormat>BP-{0000}</displayFormat>
        <label>Bookstore Publisher Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookstore Publishers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bookstore_Publisher__c/fields/Bookstore__c.field-meta.xml
<CustomField>
    <fullName>Bookstore__c</fullName>
    <label>Bookstore</label>
    <referenceTo>Bookstore__c</referenceTo>
    <relationshipName>Bookstore_Publishers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Bookstore_Publisher__c/fields/Publisher__c.field-meta.xml
<CustomField>
    <fullName>Publisher__c</fullName>
    <label>Publisher</label>
    <referenceTo>Publisher__c</referenceTo>
    <relationshipName>Bookstore_Publishers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Publisher__c/Publisher__c.object-meta.xml
<CustomObject>
    <label>Publisher</label>
    <nameField>
        <label>Publisher Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Publishers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/test/default/classes/unit/BookReservationValidationServiceTest.cls
/**
 * this class perfomrs unit tests for BookReservationValidationService class
 * 
 * @see BookReservationValidationService.cls
 */
@isTest
public with sharing class BookReservationValidationServiceTest {
    @isTest
    public static void validateSelectedBook_WillUseCorrectSelector() {
        // create data
        TestFactory testFactory = new TestFactory();
        Bookstore__c bookstore = testFactory.createBookstore(true);
        Publisher__c publisher = testFactory.createPublisher(true);
        Author__c author = testFactory.createAuthor(true);
        Bookstore_Publisher__c bookstorePublisher = testFactory.createBookstorePublisher(publisher.Id, bookstore.Id, true);
        Author_Publisher__c authorPublisher = testFactory.createAuthorPublisher(author.Id, publisher.Id, true);
        Book__c book = testFactory.createPaperBook(publisher.Id, author.Id, true);
        Bookstore_Book__c bookstoreBook = testFactory.createBookstoreBook(book.Id, bookstore.Id, true);
        Book_Reservation__c bookReservation = testFactory.createBookReservation(bookstore.Id, book.Id, true);

        // create mocks
        Mocker bookstoreBookSelectorMock = new Mocker(BookstoreBookSelector.class)
        .setBehavior('getListByBookstoreAndBookIds', new List<Bookstore_Book__c>());
        ObjectFactory.mocks.put(
            BookstoreBookSelector.class.getName(),
            (BookstoreBookSelector)bookstoreBookSelectorMock.getMock()
        );

        // execute
        BookReservationValidationService bookReservationValidationService = new BookReservationValidationService();
        bookReservationValidationService.validateSelectedBook(null, new List<Book_Reservation__c>{bookReservation});

        // assert
        bookstoreBookSelectorMock.assertMethodExecutionCount('getListByBookstoreAndBookIds', 1);
    }

    @isTest
    public static void validateSelectedBook_WillNotAddError_IfThereIsBookInBookstore() {
        // create data
        TestFactory testFactory = new TestFactory();
        Bookstore__c bookstore = testFactory.createBookstore(false);
        insert bookstore;
        Publisher__c publisher = testFactory.createPublisher(false);
        insert publisher;
        Author__c author = testFactory.createAuthor(false);
        insert author;
        Bookstore_Publisher__c bookstorePublisher = testFactory.createBookstorePublisher(publisher.Id, bookstore.Id, false);
        insert bookstorePublisher;
        Author_Publisher__c authorPublisher = testFactory.createAuthorPublisher(author.Id, publisher.Id, false);
        insert authorPublisher;
        Book__c book = testFactory.createPaperBook(publisher.Id, author.Id, false);
        insert book;
        Bookstore_Book__c bookstoreBook = testFactory.createBookstoreBook(book.Id, bookstore.Id, false);
        insert bookstoreBook;
        Book_Reservation__c bookReservation = testFactory.createBookReservation(bookstore.Id, book.Id, false);
        insert bookReservation;

        // execute
        BookReservationValidationService bookReservationValidationService = new BookReservationValidationService();
        bookReservationValidationService.validateSelectedBook(null, new List<Book_Reservation__c>{bookReservation});

        // assert
        Assert.isTrue(bookReservation.getErrors().size() == 0);
    }
    
    @isTest
    public static void validateSelectedBook_WillAddError_IfThereIsNoBookInSelectedBookstoreWhenRecordIsBeingCreated() {
       // create data
       TestFactory testFactory = new TestFactory();
       Bookstore__c bookstore = testFactory.createBookstore(true);
       Publisher__c publisher = testFactory.createPublisher(true);
       Author__c author = testFactory.createAuthor(true);
       Bookstore_Publisher__c bookstorePublisher = testFactory.createBookstorePublisher(publisher.Id, bookstore.Id, true);
       Author_Publisher__c authorPublisher = testFactory.createAuthorPublisher(author.Id, publisher.Id, true);
       Book__c book = testFactory.createPaperBook(publisher.Id, author.Id, true);
       Bookstore_Book__c bookstoreBook = testFactory.createBookstoreBook(book.Id, bookstore.Id, true);
       Book_Reservation__c bookReservation = testFactory.createBookReservation(bookstore.Id, book.Id, true);

       // create mocks
       Mocker bookstoreBookSelectorMock = new Mocker(BookstoreBookSelector.class)
       .setBehavior('getListByBookstoreAndBookIds', new List<Bookstore_Book__c>());
       ObjectFactory.mocks.put(
           BookstoreBookSelector.class.getName(),
           (BookstoreBookSelector)bookstoreBookSelectorMock.getMock()
       );

       // execute
       BookReservationValidationService bookReservationValidationService = new BookReservationValidationService();
       bookReservationValidationService.validateSelectedBook(null, new List<Book_Reservation__c>{bookReservation});

       // assert
       Assert.isTrue(bookReservation.getErrors().size() == 1);
       Assert.areEqual('There is no selected Book in selected Bookstore!', bookReservation.getErrors()[0].getMessage());
    }
    
    @isTest
    public static void validateSelectedBook_WillAddError_IfThereIsNoBookInBookstoreWhenRecordIsBeingUpdated() {
        // create data
        TestFactory testFactory = new TestFactory();
        Bookstore__c bookstore = testFactory.createBookstore(false);
        insert bookstore;
        Publisher__c publisher = testFactory.createPublisher(false);
        insert publisher;
        Author__c author = testFactory.createAuthor(false);
        insert author;
        Bookstore_Publisher__c bookstorePublisher = testFactory.createBookstorePublisher(publisher.Id, bookstore.Id, false);
        insert bookstorePublisher;
        Author_Publisher__c authorPublisher = testFactory.createAuthorPublisher(author.Id, publisher.Id, false);
        insert authorPublisher;
        Book__c book = testFactory.createPaperBook(publisher.Id, author.Id, false);
        insert book;
        Bookstore_Book__c bookstoreBook = testFactory.createBookstoreBook(book.Id, bookstore.Id, false);
        insert bookstoreBook;
        Book_Reservation__c bookReservation = testFactory.createBookReservation(bookstore.Id, book.Id, false);
        insert bookReservation;
        delete bookstoreBook;
        bookReservation.Quantity__c = 2;

        Test.startTest();
        Database.SaveResult updateResult = Database.update(bookReservation, false);
        Test.stopTest();

        Assert.isTrue(updateResult.getErrors().size() == 1);
        Assert.areEqual('There is no selected Book in selected Bookstore!', updateResult.getErrors()[0].getMessage());
    }


    @isTest
    public static void validateSelectedBook_WillAddError_IfThereAreNoEnoughBooksWhenRecordIsBeingInserted() {
        // create data
        TestFactory testFactory = new TestFactory();
        Bookstore__c bookstore = testFactory.createBookstore(false);
        insert bookstore;
        Publisher__c publisher = testFactory.createPublisher(false);
        insert publisher;
        Author__c author = testFactory.createAuthor(false);
        insert author;
        Bookstore_Publisher__c bookstorePublisher = testFactory.createBookstorePublisher(publisher.Id, bookstore.Id, false);
        insert bookstorePublisher;
        Author_Publisher__c authorPublisher = testFactory.createAuthorPublisher(author.Id, publisher.Id, false);
        insert authorPublisher;
        Book__c book = testFactory.createPaperBook(publisher.Id, author.Id, false);
        insert book;
        Bookstore_Book__c bookstoreBook = testFactory.createBookstoreBook(book.Id, bookstore.Id, false);
        insert bookstoreBook;
        Book_Reservation__c bookReservation = new Book_Reservation__c(Bookstore__c = bookstore.Id, Book__c = book.Id, Quantity__c = 11, Price__c = 10.59);

        Test.startTest();
        Database.SaveResult insertResult = Database.insert(bookReservation, false);
        Test.stopTest();

        Assert.isTrue(insertResult.getErrors().size() == 1);
        Assert.areEqual('There are no enough books! You can choose up to 10.', insertResult.getErrors()[0].getMessage());
    }

    @isTest
    public static void validateSelectedBook_WillAddError_IfThereAreNoEnoughBooksWhenRecordIsBeingUpdated() {
        // create data
        TestFactory testFactory = new TestFactory();
        Bookstore__c bookstore = testFactory.createBookstore(false);
        insert bookstore;
        Publisher__c publisher = testFactory.createPublisher(false);
        insert publisher;
        Author__c author = testFactory.createAuthor(false);
        insert author;
        Bookstore_Publisher__c bookstorePublisher = testFactory.createBookstorePublisher(publisher.Id, bookstore.Id, false);
        insert bookstorePublisher;
        Author_Publisher__c authorPublisher = testFactory.createAuthorPublisher(author.Id, publisher.Id, false);
        insert authorPublisher;
        Book__c book = testFactory.createPaperBook(publisher.Id, author.Id, false);
        insert book;
        Bookstore_Book__c bookstoreBook = testFactory.createBookstoreBook(book.Id, bookstore.Id, false);
        insert bookstoreBook;
        Book_Reservation__c bookReservation = testFactory.createBookReservation(bookstore.Id, book.Id, false);
        insert bookReservation;
        bookReservation.Quantity__c = 11;

        Test.startTest();
        Database.SaveResult updateResult = Database.update(bookReservation, false);
        Test.stopTest();

        Assert.isTrue(updateResult.getErrors().size() == 1);
        Assert.areEqual('There are no enough books! You can choose up to 10.', updateResult.getErrors()[0].getMessage());
    }

    @isTest
    public static void validateSelectedBook_WillAddOneError_IfOneBookOutOfTwoIsNotAddedToBookstoreWhenRecordIsBeingCreated() {
        // create data
        TestFactory testFactory = new TestFactory();
        Bookstore__c bookstore = testFactory.createBookstore(false);
        insert bookstore;
        Publisher__c publisher = testFactory.createPublisher(false);
        insert publisher;
        Author__c author = testFactory.createAuthor(false);
        insert author;
        Bookstore_Publisher__c bookstorePublisher = testFactory.createBookstorePublisher(publisher.Id, bookstore.Id, false);
        insert bookstorePublisher;
        Author_Publisher__c authorPublisher = testFactory.createAuthorPublisher(author.Id, publisher.Id, false);
        insert authorPublisher;
        Book__c book = testFactory.createPaperBook(publisher.Id, author.Id, false);
        insert book;
        Bookstore_Book__c bookstoreBook = testFactory.createBookstoreBook(book.Id, bookstore.Id, false);
        insert bookstoreBook;
        Book_Reservation__c bookReservation1 = new Book_Reservation__c(Bookstore__c = bookstore.Id, Book__c = book.Id, Quantity__c = 1, Price__c = 10.59);
        Book__c book1 = testFactory.createPaperBook(publisher.Id, author.Id, false);
        book1.ISBN__c = '124462465';
        insert book1;
        Book_Reservation__c bookReservation2 = new Book_Reservation__c(Bookstore__c = bookstore.Id, Book__c = book1.Id, Quantity__c = 1, Price__c = 10.59);

        List<Book_Reservation__c> reservations = new List<Book_Reservation__c>{bookReservation1, bookReservation2};

        Test.startTest();
        List<Database.SaveResult> insertResults = Database.insert(reservations, false);
        Test.stopTest();

        Assert.isTrue(insertResults[0].isSuccess());
        Assert.isFalse(insertResults[1].isSuccess());
        Assert.isTrue(insertResults[1].getErrors().size() == 1);
        Assert.areEqual('There is no selected Book in selected Bookstore!', insertResults[1].getErrors()[0].getMessage());
    }

    @isTest
    public static void validateSelectedBook_WillAddOneError_IfOneBookOutOfTwoIsNotAddedToBookstoreWhenRecordIsBeingUpdated() {
        // create data
        TestFactory testFactory = new TestFactory();
        Bookstore__c bookstore = testFactory.createBookstore(false);
        insert bookstore;
        Publisher__c publisher = testFactory.createPublisher(false);
        insert publisher;
        Author__c author = testFactory.createAuthor(false);
        insert author;
        Bookstore_Publisher__c bookstorePublisher = testFactory.createBookstorePublisher(publisher.Id, bookstore.Id, false);
        insert bookstorePublisher;
        Author_Publisher__c authorPublisher = testFactory.createAuthorPublisher(author.Id, publisher.Id, false);
        insert authorPublisher;
        Book__c book = testFactory.createPaperBook(publisher.Id, author.Id, false);
        insert book;
        Bookstore_Book__c bookstoreBook = testFactory.createBookstoreBook(book.Id, bookstore.Id, false);
        insert bookstoreBook;
        Book_Reservation__c bookReservation1 = testFactory.createBookReservation(bookstore.Id, book.Id, false);
        insert bookReservation1;
        Book__c book1 = testFactory.createPaperBook(publisher.Id, author.Id, false);
        book1.ISBN__c = '21453425';
        insert book1;
        Bookstore_Book__c bookstoreBook1 = testFactory.createBookstoreBook(book1.Id, bookstore.Id, false);
        insert bookstoreBook1;
        Book_Reservation__c bookReservation2 = testFactory.createBookReservation(bookstore.Id, book1.Id, false);
        insert bookReservation2;
        delete bookstoreBook1;
        bookReservation1.Quantity__c = 3;
        bookReservation2.Quantity__c = 4;

        List<Book_Reservation__c> reservations = new List<Book_Reservation__c>{bookReservation1, bookReservation2};

        Test.startTest();
        List<Database.SaveResult> updateResults = Database.update(reservations, false);
        Test.stopTest();

        Assert.isTrue(updateResults[0].isSuccess());
        Assert.isFalse(updateResults[1].isSuccess());
        Assert.isTrue(updateResults[1].getErrors().size() == 1);
        Assert.areEqual('There is no selected Book in selected Bookstore!', updateResults[1].getErrors()[0].getMessage());
    }
}