force-app/main/default/objects/Author__c/Author__c.object-meta.xml
<CustomObject>
    <label>Author</label>
    <nameField>
        <displayFormat>AP-{0000}</displayFormat>
        <label>Author Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Authors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Author_Publisher__c/Author_Publisher__c.object-meta.xml
<CustomObject>
    <label>Author_Publisher</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Author_Publisher Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Author_Publishers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Author_Publisher__c/fields/Author__c.field-meta.xml
<CustomField>
    <fullName>Author__c</fullName>
    <label>Author</label>
    <referenceTo>Author__c</referenceTo>
    <relationshipLabel>Author_Publishers</relationshipLabel>
    <relationshipName>Author_Publishers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Author_Publisher__c/fields/Publisher__c.field-meta.xml
<CustomField>
    <fullName>Publisher__c</fullName>
    <label>Publisher</label>
    <referenceTo>Publisher__c</referenceTo>
    <relationshipLabel>Author_Publishers</relationshipLabel>
    <relationshipName>Author_Publishers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Book__c/Book__c.object-meta.xml
<CustomObject>
    <label>Book</label>
    <nameField>
        <label>Book Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Books</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Book__c/fields/Author__c.field-meta.xml
<CustomField>
    <fullName>Author__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Author</label>
    <referenceTo>Author__c</referenceTo>
    <relationshipLabel>Books</relationshipLabel>
    <relationshipName>Books</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Book__c/fields/ISBN__c.field-meta.xml
<CustomField>
    <fullName>ISBN__c</fullName>
    <description>Unique book identifier</description>
    <inlineHelpText>Unique book identifier</inlineHelpText>
    <label>ISBN</label>
    <length>13</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Book__c/fields/Publisher__c.field-meta.xml
<CustomField>
    <fullName>Publisher__c</fullName>
    <label>Publisher</label>
    <referenceTo>Publisher__c</referenceTo>
    <relationshipLabel>Books</relationshipLabel>
    <relationshipName>Books</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Publisher__c/Publisher__c.object-meta.xml
<CustomObject>
    <label>Publisher</label>
    <nameField>
        <label>Publisher Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Publishers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/test/default/classes/integration/BookRestApiIntegrationTest.cls
/**
 * Class used for performing integration test for BookRestApi
 */
@isTest
public with sharing class BookRestApiIntegrationTest {
    @isTest
    public static void doPost_willInsertBookRecords_ifThereAreNotDuplicatesAndOptionEqualsToOne() {
        // create data
        TestFactory testFactory = new TestFactory();
        Publisher__c publisherForTest = testFactory.createPublisher(false);
        insert publisherForTest;
        Author__c authorForTest = testFactory.createAuthor(false);
        insert authorForTest;
        Author_Publisher__c authorPublisherForTest = testFactory.createAuthorPublisher(authorForTest.Id, publisherForTest.Id, false);
        insert authorPublisherForTest;
        Book__c book1 = testFactory.createBook(publisherForTest.Id, authorForTest.Id, false);
        Book__c book2 = testFactory.createBook(publisherForTest.Id, authorForTest.Id, false);
        book2.ISBN__c = '21542675223';

        // Set up the REST Request
        RestRequest request = new RestRequest();
        request.requestURI = '/services/apexrest/api/Book__c/';
        request.httpMethod = 'POST';
        Map<String, Object> reqBody = new Map<String, Object>();
        reqBody.put('data', new List<Book__c>{ book1, book2 });
        reqBody.put('option', 1);
        request.requestBody = Blob.valueOf(JSON.serialize(reqBody));

        // Set up the REST response
        RestResponse response = new RestResponse();
        RestContext.request = request;
        RestContext.response = response;

        // execute
        Test.startTest();
        BookRestApi.doPost();
        Test.stopTest();

        // Assert
        Assert.areEqual(200, response.statusCode);
    }
}