force-app/main/default/objects/Author__c/Author__c.object-meta.xml
<CustomObject>
    <label>Author</label>
    <nameField>
        <displayFormat>AP-{0000}</displayFormat>
        <label>Author Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Authors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Book__c/Book__c.object-meta.xml
<CustomObject>
    <label>Book</label>
    <nameField>
        <label>Book Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Books</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Book__c/fields/Author__c.field-meta.xml
<CustomField>
    <fullName>Author__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Author</label>
    <referenceTo>Author__c</referenceTo>
    <relationshipLabel>Books</relationshipLabel>
    <relationshipName>Books</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Book__c/fields/Publisher__c.field-meta.xml
<CustomField>
    <fullName>Publisher__c</fullName>
    <label>Publisher</label>
    <referenceTo>Publisher__c</referenceTo>
    <relationshipLabel>Books</relationshipLabel>
    <relationshipName>Books</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Book_Purchase__c/Book_Purchase__c.object-meta.xml
<CustomObject>
    <label>Book Purchase</label>
    <nameField>
        <displayFormat>BP-{0000}</displayFormat>
        <label>Book Purchase Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Book Purchases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Book_Purchase__c/fields/Book__c.field-meta.xml
<CustomField>
    <fullName>Book__c</fullName>
    <label>Book</label>
    <referenceTo>Book__c</referenceTo>
    <relationshipLabel>Book Purchases</relationshipLabel>
    <relationshipName>Book_Purchases</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Publisher__c/Publisher__c.object-meta.xml
<CustomObject>
    <label>Publisher</label>
    <nameField>
        <label>Publisher Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Publishers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/test/default/classes/unit/BookPurchaseValidationServiceTest.cls
/*
 * This class is used for testing book purchase validation service
 * There will be 1 positive, 1 negative and 1 mockerexecutioncount tests
 */
@isTest
public with sharing class BookPurchaseValidationServiceTest {
    /*
     * Reason why we have no mocks in this method is because the code will add error before the selector is even executed
     */
    @isTest
    public static void validatePurchase_willAddError_ifTwoSamePurchasesAreInsertedAtOnce() {
        // create data
        TestFactory testFactory = new TestFactory();
        Publisher__c publisherForTest = testFactory.createPublisher(false, true);
        Author__c authorForTest = testFactory.createAuthor(false, true);
        Book__c bookForTest = testFactory.createBook(publisherForTest.Id, authorForTest.Id, false, true);
        Book_Purchase__c purchaseForTest = testFactory.createBookPurchase(bookForTest.Id, false, true);

        // execute
        BookPurchaseValidationService service = new BookPurchaseValidationService();
        service.validatePurchase(new List<Book_Purchase__c>{purchaseForTest, purchaseForTest});

        // assert
        Assert.isTrue(purchaseForTest.getErrors().size() == 1);
    }

    @isTest
    public static void validatePurchase_wilNotAddError_ifNoSamePurchasesExist() {
        // create data
        TestFactory testFactory = new TestFactory();
        Publisher__c publisherForTest = testFactory.createPublisher(false, true);
        Author__c authorForTest = testFactory.createAuthor(false, true);
        Book__c bookForTest = testFactory.createBook(publisherForTest.Id, authorForTest.Id, false, true);
        Book_Purchase__c purchaseForTest = testFactory.createBookPurchase(bookForTest.Id, false, true);
        
        // create mock
        Mocker BookPurchaseSelectorMock = new Mocker(BookPurchaseSelector.class)
            .setBehavior('getList', new List<Book_Purchase__c>());
        ObjectFactory.mocks.put(
            BookPurchaseSelector.class.getName(),
            (BookPurchaseSelector) BookPurchaseSelectorMock.getMock()
        );

        // execute
        BookPurchaseValidationService service = new BookPurchaseValidationService();
        service.validatePurchase(new List<Book_Purchase__c>{purchaseForTest});

        // assert
        Assert.isTrue(purchaseForTest.getErrors().size() == 0);
    }

    @isTest
    public static void validatePurchase_willUseCorrectSelector() {
        // create data
        TestFactory testFactory = new TestFactory();
        Publisher__c publisherForTest = testFactory.createPublisher(false, true);
        Author__c authorForTest = testFactory.createAuthor(false, true);
        Book__c bookForTest = testFactory.createBook(publisherForTest.Id, authorForTest.Id, false, true);
        Book_Purchase__c purchaseForTest = testFactory.createBookPurchase(bookForTest.Id, false, true);
        
        // create mock
        Mocker BookPurchaseSelectorMock = new Mocker(BookPurchaseSelector.class)
            .setBehavior('getList', new List<Book_Purchase__c>());
        ObjectFactory.mocks.put(
            BookPurchaseSelector.class.getName(),
            (BookPurchaseSelector) BookPurchaseSelectorMock.getMock()
        );

        // execute
        BookPurchaseValidationService service = new BookPurchaseValidationService();
        service.validatePurchase(new List<Book_Purchase__c>{purchaseForTest});

        // assert
        BookPurchaseSelectorMock.assertMethodExecutionCount('getList', 1);
    }
}