force-app/main/default/objects/Author__c/Author__c.object-meta.xml
<CustomObject>
    <label>Author</label>
    <nameField>
        <displayFormat>AP-{0000}</displayFormat>
        <label>Author Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Authors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Book__c/Book__c.object-meta.xml
<CustomObject>
    <label>Book</label>
    <nameField>
        <label>Book Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Books</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Book__c/fields/Author__c.field-meta.xml
<CustomField>
    <fullName>Author__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Author</label>
    <referenceTo>Author__c</referenceTo>
    <relationshipLabel>Books</relationshipLabel>
    <relationshipName>Books</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Book__c/fields/Categories__c.field-meta.xml
<CustomField>
    <fullName>Categories__c</fullName>
    <description>Genres the book belongs to</description>
    <inlineHelpText>Genres the book belongs to</inlineHelpText>
    <label>Categories</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Book__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Book description</description>
    <inlineHelpText>Book description</inlineHelpText>
    <label>Description</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Book__c/fields/ISBN__c.field-meta.xml
<CustomField>
    <fullName>ISBN__c</fullName>
    <description>Unique book identifier</description>
    <inlineHelpText>Unique book identifier</inlineHelpText>
    <label>ISBN</label>
    <length>13</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Book__c/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <description>Language of the Book</description>
    <inlineHelpText>Language of the Book</inlineHelpText>
    <label>Language</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Book__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Price</label>
    <precision>17</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Book__c/fields/Publish_Date__c.field-meta.xml
<CustomField>
    <fullName>Publish_Date__c</fullName>
    <description>Book publish date</description>
    <inlineHelpText>Book publish date</inlineHelpText>
    <label>Publish Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Book__c/fields/Publisher__c.field-meta.xml
<CustomField>
    <fullName>Publisher__c</fullName>
    <label>Publisher</label>
    <referenceTo>Publisher__c</referenceTo>
    <relationshipLabel>Books</relationshipLabel>
    <relationshipName>Books</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Bookstore__c/Bookstore__c.object-meta.xml
<CustomObject>
    <label>Bookstore</label>
    <nameField>
        <label>Bookstore Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookstores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Bookstore__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Bookstore_Book__c/Bookstore_Book__c.object-meta.xml
<CustomObject>
    <label>Bookstore_Book</label>
    <nameField>
        <label>Bookstore_Book Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookstore_Books</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bookstore_Book__c/fields/Book__c.field-meta.xml
<CustomField>
    <fullName>Book__c</fullName>
    <label>Book</label>
    <referenceTo>Book__c</referenceTo>
    <relationshipLabel>Bookstore Books</relationshipLabel>
    <relationshipName>Bookstore_Books</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Bookstore_Book__c/fields/Bookstore__c.field-meta.xml
<CustomField>
    <fullName>Bookstore__c</fullName>
    <label>Bookstore</label>
    <referenceTo>Bookstore__c</referenceTo>
    <relationshipLabel>Bookstore Books</relationshipLabel>
    <relationshipName>Bookstore_Books</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Publisher__c/Publisher__c.object-meta.xml
<CustomObject>
    <label>Publisher</label>
    <nameField>
        <label>Publisher Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Publishers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/Service/BookSearchService.cls
/**
 * Book search service class used to hold business logic for the
 * BookController
 * 
 * @see BookController.cls
 * @see BookSelector.cls
 * @see BookReviewSelector.cls
 * @see BookSearchDTO.cls
 */
public with sharing class BookSearchService implements CustomObject{
    /**
     * List of Books containging book information that will be returned to Controller as a response
     */
    private List<Book__c> response;

    /**
     * Getter method for response property
     * 
     * @return this class's response property value
     */
    public List<Book__c> getResponse() {
        return this.response;
    }

    /**
     * Setter method for response property
     * 
     * @param response List of Books containging book information that we want to assign to response field
     */
    public void setResponse(List<Book__c> response) {
        this.response = response;
    }

    /**
     * Returns conjunction (WHERE/AND) to append to query conditions depending on weather WHERE clause was already started or not
     * 
     * @param queryConditions - Query conditions the conjunction is getting appended to
     */
    public String getQueryConjunction(String queryConditions){
        if (!String.isBlank(queryConditions)){
            return ' AND ';
        }

        else {
            return 'WHERE ';
        }
    }

    /**
     * Generates query conditions based on recieved bookSearchDTO
     * Calls BookSelector method to get a list of book information based on these query conditions
     * Further filters book list by description term and minimum review score if they are set as search keys
     * Sets response property to searched and filtered book list
     * 
     * @param bookSearchDTO - Object containing all relevant search keys
     * @param limitSize - Maximum number of records to return
     * @param offset - Offset for querying records
     * 
     */
    public void getBooksFromSearchDTO(BookSearchDTO bookSearchDTO, Integer limitSize, Integer offset) {
        if (bookSearchDTO == null) {
            this.setResponse(null);
        }
        
        else {
            BookSelector bookSelector = (BookSelector) new ObjectFactory().createObject(BookSelector.class);
            BookReviewSelector bookReviewSelector = (BookReviewSelector) new ObjectFactory().createObject(BookReviewSelector.class);
            String bookQueryConditions='';
            
            if (!String.isBlank(bookSearchDTO.name)){
                bookQueryConditions+=String.format('WHERE Name LIKE \'%{0}%\'', new String[] { bookSearchDTO.name.trim() });
            }

            if (!String.isBlank(bookSearchDTO.ISBN)){
                bookQueryConditions+= getQueryConjunction(bookQueryConditions);
                bookQueryConditions+=String.format('ISBN__c LIKE \'%{0}%\'', new String[] { bookSearchDTO.ISBN.trim() });
            }

            if (!String.isBlank(bookSearchDTO.author)){
                bookQueryConditions+= getQueryConjunction(bookQueryConditions);
                bookQueryConditions+='Author__c=\''+bookSearchDTO.author+'\'';
            }

            if (bookSearchDTO.publishDate!=null){
                bookQueryConditions+= getQueryConjunction(bookQueryConditions);
                //Creates DateTime from Date object to enable custom formatting
                Datetime publishDateTime=Datetime.newInstance(
                    bookSearchDTO.publishDate.year(),
                    bookSearchDTO.publishDate.month(),
                    bookSearchDTO.publishDate.day()
                );
                bookQueryConditions+=String.format('Publish_Date__c={0}', new String[] { publishDateTime.format('yyyy-MM-dd') });
            }

            if (!String.isBlank(bookSearchDTO.bookstore)){
                bookQueryConditions+= getQueryConjunction(bookQueryConditions);
                bookQueryConditions+='Id IN (SELECT Book__c FROM Bookstore_Book__c WHERE Bookstore__c= \''+bookSearchDTO.bookstore+'\' )';
            }

            if (!String.isBlank(bookSearchDTO.publisher)){
                bookQueryConditions+= getQueryConjunction(bookQueryConditions);
                bookQueryConditions+='Publisher__c=\''+bookSearchDTO.publisher+'\'';
            }

            if (bookSearchDTO.categories!=null && bookSearchDTO.categories.size()>0){
                bookQueryConditions+= getQueryConjunction(bookQueryConditions);
                String concatedCategories='';

                //Concats categories from an array to a string form suitable for an SOQL query
                for(Integer i=0;i<bookSearchDTO.categories.size();i++){
                    concatedCategories+=bookSearchDTO.categories[i];

                    if (i<bookSearchDTO.categories.size()-1){
                        concatedCategories+=';';
                    }
                }
                bookQueryConditions+=String.format('Categories__c includes (\' {0} \')', new String[] { concatedCategories });
            }

            if (bookSearchDTO.languages!=null && bookSearchDTO.languages.size()>0){
                bookQueryConditions+= getQueryConjunction(bookQueryConditions);
                String concatedLanguages='';

                //Concats languages from an array to a string form suitable for an SOQL query
                for(Integer i=0;i<bookSearchDTO.languages.size();i++){
                    concatedLanguages+='\''+bookSearchDTO.languages[i]+'\'';

                    if (i<bookSearchDTO.languages.size()-1){
                        concatedLanguages+=',';
                    }
                }
                bookQueryConditions+=String.format('Language__c in ({0})', new String[] { concatedLanguages });
            }

            if (bookSearchDTO.price!=null && bookSearchDTO.price>0){
                bookQueryConditions+= getQueryConjunction(bookQueryConditions);
                bookQueryConditions+=String.format('Price__c<={0}', new String[] { bookSearchDTO.price.format() });
            }

            if (limitSize!=null && limitSize>0){
                bookQueryConditions+=String.format(' LIMIT {0}', new String[] { String.valueOf(limitSize) });
            }
            
            else {
                bookQueryConditions+=' LIMIT 2000';
            }

            if (offset!=null && offset>0){
                bookQueryConditions+=String.format(' OFFSET {0}', new String[] { String.valueOf(offset) });
            }

            //queries books as a list 
            List<Book__c> searchedAndFilteredBooks=bookSelector.getListFromQueryConditions(bookQueryConditions);

            /**
             * If minimum review score set as search key, makes map of queried books
             * The keyset of that map is used as a parameter for the getAverageRatingListByBookIdSet method of the bookReviewSelector
             */
            if (bookSearchDTO.reviewScore!=null && bookSearchDTO.reviewScore>0){
                Map<Id, Book__c> searchedBookMap = new Map<Id, Book__c>(searchedAndFilteredBooks);
                List<AggregateResult> averageRatigsList = bookReviewSelector.getAverageRatingListByBookIdSet(searchedBookMap.keySet());
                List<Book__c> booksWithPassingReview = new List<Book__c>();

                //For each average review score, if it matches search criteria, adds the associated book to a filtered list
                for (AggregateResult averageRating:averageRatigsList){

                    if ((Decimal)averageRating.get('Rating')>=bookSearchDTO.reviewScore){
                        booksWithPassingReview.add(searchedBookMap.get((Id)averageRating.get('Book__c')));
                    }
                }
                searchedAndFilteredBooks=booksWithPassingReview;
            }

            //If term set as search key, filters existing book list to contain only books whose decriptions contain the term
            if (!String.isBlank(bookSearchDTO.term)){
                List<Book__c> booksWithMatchingDescription = new List<Book__c>();

                for (Book__c book:searchedAndFilteredBooks){

                    if (book.Description__c.toLowerCase().contains( bookSearchDTO.term.trim().toLowerCase() )){
                        booksWithMatchingDescription.add(book);
                    }
                }
                searchedAndFilteredBooks=booksWithMatchingDescription;
            }

            this.setResponse(searchedAndFilteredBooks);
        }
    }
}