force-app/main/default/objects/Author__c/Author__c.object-meta.xml
<CustomObject>
    <label>Author</label>
    <nameField>
        <displayFormat>AP-{0000}</displayFormat>
        <label>Author Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Authors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Author_Publisher__c/Author_Publisher__c.object-meta.xml
<CustomObject>
    <label>Author_Publisher</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Author_Publisher Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Author_Publishers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Author_Publisher__c/fields/Author__c.field-meta.xml
<CustomField>
    <fullName>Author__c</fullName>
    <label>Author</label>
    <referenceTo>Author__c</referenceTo>
    <relationshipLabel>Author_Publishers</relationshipLabel>
    <relationshipName>Author_Publishers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Author_Publisher__c/fields/Publisher__c.field-meta.xml
<CustomField>
    <fullName>Publisher__c</fullName>
    <label>Publisher</label>
    <referenceTo>Publisher__c</referenceTo>
    <relationshipLabel>Author_Publishers</relationshipLabel>
    <relationshipName>Author_Publishers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Publisher__c/Publisher__c.object-meta.xml
<CustomObject>
    <label>Publisher</label>
    <nameField>
        <label>Publisher Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Publishers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/test/default/classes/unit/AuthorPublisherVFControllerTest.cls
/**
 * Class tests selector execution account in AuthorPublisherVFController services
 * Every test requires data to be made so the controller can even be instantiated
 * Every test will require mocking the AuthorPublisherSelector class, because it runs in the constructor
 * Controller must be instantaiated because it is an extension of standard controller
 */
@isTest
public with sharing class AuthorPublisherVFControllerTest {
    @isTest
    public static void getBooksCausingError_willUseService() {
        // create data
        TestFactory testFactory = new TestFactory();
        Publisher__c publisherForTest = testFactory.createPublisher(true);
        Author__c authorForTest = testFactory.createAuthor(true);
        Author_Publisher__c authorPublisherForTest = testFactory
            .createAuthorPublisher(publisherForTest.Id, authorForTest.Id, true);
        ApexPages.StandardController stdController = new ApexPages.StandardController(authorPublisherForTest);

        // create mocks
        Mocker authorPublisherSelectorMocker = new Mocker(AuthorPublisherSelector.class)
            .setBehavior('getRecordById', authorPublisherForTest);
        ObjectFactory.mocks.put(
            AuthorPublisherSelector.class.getName(),
            (AuthorPublisherSelector) authorPublisherSelectorMocker.getMock()
        );

        Mocker getRelatedBooksOnAuthPubDelServiceMocker = new Mocker(GetRelatedBooksOnAuthPubDelService.class);
        getRelatedBooksOnAuthPubDelServiceMocker.setBehavior('getRelatedBooks', null);
        getRelatedBooksOnAuthPubDelServiceMocker.setBehavior('getResponse', null);
        ObjectFactory.mocks.put(
            GetRelatedBooksOnAuthPubDelService.class.getName(),
            (GetRelatedBooksOnAuthPubDelService) getRelatedBooksOnAuthPubDelServiceMocker.getMock()
        );

        // execute
        AuthorPublisherVFController controller = new AuthorPublisherVFController(stdController);
        controller.getBooksCausingError();

        // assert 
        getRelatedBooksOnAuthPubDelServiceMocker.assertMethodExecutionCount('getRelatedBooks', 1);
        getRelatedBooksOnAuthPubDelServiceMocker.assertMethodExecutionCount('getResponse', 1);
    }

    @isTest
    public static void getPageReference_willUseService() {
        // create data
        TestFactory testFactory = new TestFactory();
        Publisher__c publisherForTest = testFactory.createPublisher(true);
        Author__c authorForTest = testFactory.createAuthor(true);
        Author_Publisher__c authorPublisherForTest = testFactory
            .createAuthorPublisher(authorForTest.Id, publisherForTest.Id, true);
        ApexPages.StandardController stdController = new ApexPages.StandardController(authorPublisherForTest);

        // create mocks
        Mocker authorPublisherSelectorMocker = new Mocker(AuthorPublisherSelector.class)
            .setBehavior('getRecordById', authorPublisherForTest);
        ObjectFactory.mocks.put(
            AuthorPublisherSelector.class.getName(),
            (AuthorPublisherSelector) authorPublisherSelectorMocker.getMock()
        );

        Mocker pageReferenceServiceMocker = new Mocker(PageReferenceService.class);
        pageReferenceServiceMocker.setBehavior('getPageReferenceForAuthorPublisher', null);
        pageReferenceServiceMocker.setBehavior('getResponse', null);
        ObjectFactory.mocks.put(
            PageReferenceService.class.getName(),
            (PageReferenceService) pageReferenceServiceMocker.getMock()
        );

        // execute
        AuthorPublisherVFController controller = new AuthorPublisherVFController(stdController);
        controller.getPageReference();

        // assert 
        pageReferenceServiceMocker.assertMethodExecutionCount('getPageReferenceForAuthorPublisher', 1);
        pageReferenceServiceMocker.assertMethodExecutionCount('getResponse', 1);
    }

    @isTest
    public static void cancel_willUseService() {
        // create data
        TestFactory testFactory = new TestFactory();
        Publisher__c publisherForTest = testFactory.createPublisher(true);
        Author__c authorForTest = testFactory.createAuthor(true);
        Author_Publisher__c authorPublisherForTest = testFactory
            .createAuthorPublisher(publisherForTest.Id, authorForTest.Id, true);
        ApexPages.StandardController stdController = new ApexPages.StandardController(authorPublisherForTest);

        // create mocks
        Mocker AuthorPublisherSelectorMocker = new Mocker(AuthorPublisherSelector.class)
            .setBehavior('getRecordById', authorPublisherForTest);
        ObjectFactory.mocks.put(
            AuthorPublisherSelector.class.getName(),
            (AuthorPublisherSelector) AuthorPublisherSelectorMocker.getMock()
        );

        Mocker PageReferenceServiceMocker = new Mocker(PageReferenceService.class);
        PageReferenceServiceMocker.setBehavior('getPageReferenceForAuthorPublisher', null);
        PageReferenceServiceMocker.setBehavior('getResponse', null);
        ObjectFactory.mocks.put(
            PageReferenceService.class.getName(),
            (PageReferenceService) PageReferenceServiceMocker.getMock()
        );

        // execute
        AuthorPublisherVFController controller = new AuthorPublisherVFController(stdController);
        controller.cancel();
        PageReferenceServiceMocker.assertMethodExecutionCount('getPageReferenceForAuthorPublisher', 1);
        PageReferenceServiceMocker.assertMethodExecutionCount('getResponse', 1);
    }

    @isTest
    public static void viewAll_willUseService() {
        // create data
        TestFactory testFactory = new TestFactory();
        Publisher__c publisherForTest = testFactory.createPublisher(true);
        Author__c authorForTest = testFactory.createAuthor(true);
        Author_Publisher__c authorPublisherForTest = testFactory
            .createAuthorPublisher(publisherForTest.Id, authorForTest.Id, true);
        ApexPages.StandardController stdController = new ApexPages.StandardController(authorPublisherForTest);

        // create mocks
        Mocker AuthorPublisherSelectorMocker = new Mocker(AuthorPublisherSelector.class)
            .setBehavior('getRecordById', authorPublisherForTest);
        ObjectFactory.mocks.put(
            AuthorPublisherSelector.class.getName(),
            (AuthorPublisherSelector) AuthorPublisherSelectorMocker.getMock()
        );

        Mocker PageReferenceServiceMocker = new Mocker(PageReferenceService.class);
        PageReferenceServiceMocker.setBehavior('getPageReferenceForAuthorPublisher', null);
        PageReferenceServiceMocker.setBehavior('getResponse', null);
        ObjectFactory.mocks.put(
            PageReferenceService.class.getName(),
            (PageReferenceService) PageReferenceServiceMocker.getMock()
        );

        // execute
        AuthorPublisherVFController controller = new AuthorPublisherVFController(stdController);
        controller.viewAll();
        PageReferenceServiceMocker.assertMethodExecutionCount('getPageReferenceForAuthorPublisher', 1);
        PageReferenceServiceMocker.assertMethodExecutionCount('getResponse', 1);
    }

}