force-app/main/default/objects/Author__c/Author__c.object-meta.xml
<CustomObject>
    <label>Author</label>
    <nameField>
        <displayFormat>AP-{0000}</displayFormat>
        <label>Author Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Authors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Book__c/Book__c.object-meta.xml
<CustomObject>
    <label>Book</label>
    <nameField>
        <label>Book Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Books</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Book__c/fields/Author__c.field-meta.xml
<CustomField>
    <fullName>Author__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Author</label>
    <referenceTo>Author__c</referenceTo>
    <relationshipLabel>Books</relationshipLabel>
    <relationshipName>Books</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Book__c/fields/Publisher__c.field-meta.xml
<CustomField>
    <fullName>Publisher__c</fullName>
    <label>Publisher</label>
    <referenceTo>Publisher__c</referenceTo>
    <relationshipLabel>Books</relationshipLabel>
    <relationshipName>Books</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Bookstore__c/Bookstore__c.object-meta.xml
<CustomObject>
    <label>Bookstore</label>
    <nameField>
        <label>Bookstore Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookstores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Bookstore_Book__c/Bookstore_Book__c.object-meta.xml
<CustomObject>
    <label>Bookstore_Book</label>
    <nameField>
        <label>Bookstore_Book Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookstore_Books</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bookstore_Book__c/fields/Book__c.field-meta.xml
<CustomField>
    <fullName>Book__c</fullName>
    <label>Book</label>
    <referenceTo>Book__c</referenceTo>
    <relationshipLabel>Bookstore Books</relationshipLabel>
    <relationshipName>Bookstore_Books</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Bookstore_Book__c/fields/Bookstore__c.field-meta.xml
<CustomField>
    <fullName>Bookstore__c</fullName>
    <label>Bookstore</label>
    <referenceTo>Bookstore__c</referenceTo>
    <relationshipLabel>Bookstore Books</relationshipLabel>
    <relationshipName>Bookstore_Books</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Bookstore_Publisher__c/Bookstore_Publisher__c.object-meta.xml
<CustomObject>
    <label>Bookstore_Publisher</label>
    <nameField>
        <displayFormat>BP-{0000}</displayFormat>
        <label>Bookstore Publisher Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookstore Publishers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bookstore_Publisher__c/fields/Bookstore__c.field-meta.xml
<CustomField>
    <fullName>Bookstore__c</fullName>
    <label>Bookstore</label>
    <referenceTo>Bookstore__c</referenceTo>
    <relationshipName>Bookstore_Publishers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Bookstore_Publisher__c/fields/Publisher__c.field-meta.xml
<CustomField>
    <fullName>Publisher__c</fullName>
    <label>Publisher</label>
    <referenceTo>Publisher__c</referenceTo>
    <relationshipName>Bookstore_Publishers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Publisher__c/Publisher__c.object-meta.xml
<CustomObject>
    <label>Publisher</label>
    <nameField>
        <label>Publisher Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Publishers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/test/default/classes/unit/BookstoreBookValidationServiceTest.cls
/*
 *This class performs unit tests for BookstoreBookValidationService class
 *Tests consist of 2 mocks where we mock selectors
 *Both single and multiple validations are tested
 *Method Execution count will always be the same regardless of the amount of records inserted
 */
@isTest
public with sharing class BookstoreBookValidationServiceTest {
    @isTest
    public static void validatePublisher_willNotAddError_ifBookstorePublisherIsAdded() {
        // create data
        TestFactory testFactory = new TestFactory();
        Publisher__c publisherForTest = testFactory.createPublisher(false, true);
        Bookstore__c bookstoreForTest = testFactory.createBookstore(false, true);
        Author__c authorForTest = testFactory.createAuthor(false, true);
        Book__c bookForTest = testFactory.createBook(publisherForTest.Id, authorForTest.Id, false, true);
        Bookstore_Book__c bookstoreBookForTest = testFactory
        .createBookstoreBook(bookForTest.Id, bookstoreForTest.Id, false, true);
        Bookstore_Publisher__c bookStorePublisherForMock = testFactory
        .createBookstorePublisher(publisherForTest.Id, bookstoreForTest.Id, false, true);

        // create mocks
        Mocker bookSelectorMock = new Mocker(BookSelector.class)
            .setBehavior('getMapByIds', new Map<Id, Book__c>{
                bookForTest.Id => bookForTest
        });
        ObjectFactory.mocks.put(
            BookSelector.class.getName(),
            (BookSelector)bookSelectorMock.getMock()
        );
        Mocker bookStorePublisherSelectorMock = new Mocker(BookstorePublisherSelector.class)
            .setBehavior('getList', new List<Bookstore_Publisher__c>{bookStorePublisherForMock});
        ObjectFactory.mocks.put(
            BookstorePublisherSelector.class.getName(),
            (BookstorePublisherSelector) bookStorePublisherSelectorMock.getMock()
        );

        // execute
        BookstoreBookValidationService bookStoreBookValidation = new BookstoreBookValidationService();
        bookStoreBookValidation.validatePublisher(new List<Bookstore_Book__c>{bookstoreBookForTest});

        // assert
        Assert.isTrue(bookstoreBookForTest.getErrors().size() == 0);
    }
    
    @isTest
    public static void validatePublisher_willAddError_ifBookstorePublisherIsNotAdded() {
        // create data
        TestFactory testFactory = new TestFactory();
        Publisher__c publisherForTest = testFactory.createPublisher(false, true);
        Bookstore__c bookstoreForTest = testFactory.createBookstore(false, true);
        Author__c authorForTest = testFactory.createAuthor(true, false);
        Book__c bookForTest = testFactory.createBook(publisherForTest.Id, authorForTest.Id, false, true);
        Bookstore_Book__c bookstoreBookForTest = testFactory
        .createBookstoreBook(bookForTest.Id, bookstoreForTest.Id, false, true);
        
        // create mocks
        Mocker bookSelectorMock = new Mocker(BookSelector.class)
            .setBehavior('getMapByIds', new Map<Id, Book__c>{
                bookForTest.Id => bookForTest
        });
        ObjectFactory.mocks.put(
            BookSelector.class.getName(),
            (BookSelector)bookSelectorMock.getMock()
        );
        Mocker bookStorePublisherSelectorMock = new Mocker(BookstorePublisherSelector.class)
            .setBehavior('getList', new List<Bookstore_Publisher__c>());
        ObjectFactory.mocks.put(
            BookstorePublisherSelector.class.getName(),
            (BookstorePublisherSelector) bookStorePublisherSelectorMock.getMock()
        );

        // execute
        BookstoreBookValidationService bookStoreBookValidation = new BookstoreBookValidationService();
        bookStoreBookValidation.validatePublisher(new List<Bookstore_Book__c>{bookstoreBookForTest});

        // assert
        Assert.isTrue(bookstoreBookForTest.getErrors().size() == 1);
    }
    
    @isTest
    public static void validatePublisher_willUseCorrectSelectors() {
        // create data
        TestFactory testFactory = new TestFactory();
        Publisher__c publisherForTest = testFactory.createPublisher(false, true);
        Bookstore__c bookstoreForTest = testFactory.createBookstore(false, true);
        Author__c authorForTest = testFactory.createAuthor(true, false);
        Book__c bookForTest = testFactory.createBook(publisherForTest.Id, authorForTest.Id, false, true);
        Bookstore_Book__c bookstoreBookForTest = testFactory
        .createBookstoreBook(bookForTest.Id, bookstoreForTest.Id, false, true);
        
        // create mocks
        Mocker bookSelectorMock = new Mocker(BookSelector.class)
            .setBehavior('getMapByIds', new Map<Id, Book__c>{
            bookForTest.Id => bookForTest
        });
        ObjectFactory.mocks.put(
            BookSelector.class.getName(),
            (BookSelector)bookSelectorMock.getMock()
        );
        Mocker bookStorePublisherSelectorMock = new Mocker(BookstorePublisherSelector.class)
            .setBehavior('getList', new List<Bookstore_Publisher__c>());
        ObjectFactory.mocks.put(
            BookstorePublisherSelector.class.getName(),
            (BookstorePublisherSelector) bookStorePublisherSelectorMock.getMock()
        );

        // execute
        BookstoreBookValidationService bookStoreBookValidation = new BookstoreBookValidationService();
        bookStoreBookValidation.validatePublisher(new List<Bookstore_Book__c>{bookstoreBookForTest});
        
        // assert
        bookSelectorMock.assertMethodExecutionCount('getMapByIds', 1);
        bookStorePublisherSelectorMock.assertMethodExecutionCount('getList', 1);
    }
}