force-app/main/default/objects/Author__c/Author__c.object-meta.xml
<CustomObject>
    <label>Author</label>
    <nameField>
        <displayFormat>AP-{0000}</displayFormat>
        <label>Author Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Authors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Author_Publisher__c/Author_Publisher__c.object-meta.xml
<CustomObject>
    <label>Author_Publisher</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Author_Publisher Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Author_Publishers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Author_Publisher__c/fields/Author__c.field-meta.xml
<CustomField>
    <fullName>Author__c</fullName>
    <label>Author</label>
    <referenceTo>Author__c</referenceTo>
    <relationshipLabel>Author_Publishers</relationshipLabel>
    <relationshipName>Author_Publishers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Author_Publisher__c/fields/Publisher__c.field-meta.xml
<CustomField>
    <fullName>Publisher__c</fullName>
    <label>Publisher</label>
    <referenceTo>Publisher__c</referenceTo>
    <relationshipLabel>Author_Publishers</relationshipLabel>
    <relationshipName>Author_Publishers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Book__c/Book__c.object-meta.xml
<CustomObject>
    <label>Book</label>
    <nameField>
        <label>Book Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Books</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Book__c/fields/Author__c.field-meta.xml
<CustomField>
    <fullName>Author__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Author</label>
    <referenceTo>Author__c</referenceTo>
    <relationshipLabel>Books</relationshipLabel>
    <relationshipName>Books</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Book__c/fields/Publisher__c.field-meta.xml
<CustomField>
    <fullName>Publisher__c</fullName>
    <label>Publisher</label>
    <referenceTo>Publisher__c</referenceTo>
    <relationshipLabel>Books</relationshipLabel>
    <relationshipName>Books</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Publisher__c/Publisher__c.object-meta.xml
<CustomObject>
    <label>Publisher</label>
    <nameField>
        <label>Publisher Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Publishers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/Service/BookValidationService.cls
/*
* Validates if the Book__c sObject that is being created/edited has matching Author__c and Publisher__c values
* (wether an Author_Publisher__c junction sObject with matching Author__c and Publisher__c values exists)
*/
public with sharing class BookValidationService implements CustomObject{
    /*
    * @param newBooks - Newly added or edited books
    */
    public void validateAuthorPublisherMatch(List<Book__c> newBooks) {
        //Get all Author_Publisher__c sObjects
        AuthorPublisherSelector authorPublisherSelector = (AuthorPublisherSelector) new ObjectFactory().createObject(AuthorPublisherSelector.class);
        List<Author_Publisher__c> authorPublishers = authorPublisherSelector.getList();

        //Iterate through each new book
        //For each new book, iterate through Author_Publisher__c sObjects, checking if one with matching Author__c and Publisher__c fields is found
        //If matching Author_Publisher__c is not found, add error to the invalid Book__c sObject
        for (Book__c newBook:newBooks){
            Boolean isFound=false;           
            for(Author_Publisher__c authorPublisher:authorPublishers){
                if (newBook.Author__c==authorPublisher.Author__c && newBook.Publisher__c==authorPublisher.Publisher__c){
                    isFound=true;
                    break;
                }
            }
            if (!isFound) {
                newBook.addError('Book author and book publisher must work together!');
            }
        }
    }
}