force-app/main/default/objects/Author__c/Author__c.object-meta.xml
<CustomObject>
    <label>Author</label>
    <nameField>
        <displayFormat>AP-{0000}</displayFormat>
        <label>Author Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Authors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Author_Publisher__c/Author_Publisher__c.object-meta.xml
<CustomObject>
    <label>Author_Publisher</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Author_Publisher Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Author_Publishers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Author_Publisher__c/fields/Author__c.field-meta.xml
<CustomField>
    <fullName>Author__c</fullName>
    <label>Author</label>
    <referenceTo>Author__c</referenceTo>
    <relationshipLabel>Author_Publishers</relationshipLabel>
    <relationshipName>Author_Publishers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Author_Publisher__c/fields/Publisher__c.field-meta.xml
<CustomField>
    <fullName>Publisher__c</fullName>
    <label>Publisher</label>
    <referenceTo>Publisher__c</referenceTo>
    <relationshipLabel>Author_Publishers</relationshipLabel>
    <relationshipName>Author_Publishers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Book__c/Book__c.object-meta.xml
<CustomObject>
    <label>Book</label>
    <nameField>
        <label>Book Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Books</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Book__c/fields/Author__c.field-meta.xml
<CustomField>
    <fullName>Author__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Author</label>
    <referenceTo>Author__c</referenceTo>
    <relationshipLabel>Books</relationshipLabel>
    <relationshipName>Books</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Book__c/fields/Publisher__c.field-meta.xml
<CustomField>
    <fullName>Publisher__c</fullName>
    <label>Publisher</label>
    <referenceTo>Publisher__c</referenceTo>
    <relationshipLabel>Books</relationshipLabel>
    <relationshipName>Books</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Publisher__c/Publisher__c.object-meta.xml
<CustomObject>
    <label>Publisher</label>
    <nameField>
        <label>Publisher Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Publishers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/Service/AuthorPublisherDeleteValidationService.cls
/*
 * Class responsible for stopping delete of Author_Publisher__c record if a Book__c record exist with matching Author and Publisher values
 */
public with sharing class AuthorPublisherDeleteValidationService implements CustomObject{
private List<Book__c> response;

    //Getter
    public List<Book__c> getResponse() {
        return this.response;
    }

    //Setter
    public void setResponse(List<Book__c> bookList) {
        this.response = bookList;
    }

    /**
     * @param deletedRecords - Author_Publisher__c records being deleted 
     */
    public void validateAuthorPublisher(List<Author_Publisher__c> deletedRecords, Integer recordLimit) {
        // Set that holds Ids of Author__c records that correspond to the Authors of deleted records
        Set<Id> authorIds = new Set<Id>();
        // Loop through deleted records and add their Ids to the set
        for (Author_Publisher__c authorPublisher : deletedRecords) {
            authorIds.add(authorPublisher.Author__c);
        }

        // Retrieve all the Book__c records that correspond to the same Authors as deleted records
        BookSelector bookSelector = (BookSelector) new ObjectFactory()
            .createObject(BookSelector.class);
        List<Book__c> books = bookSelector.getListByAuthorIds(authorIds, recordLimit);
        
        // Loop through deleted record and retrieved Book__c and check if the Publisher corresponds to the deleted records
        List<Book__c> bookRecordsThatCauseError = new List<Book__c>();
        for (Author_Publisher__c authorPublisher : deletedRecords) {
            for (Book__c book : books) {
                if (book.Publisher__c == authorPublisher.Publisher__c) {
                    bookRecordsThatCauseError.add(Book);
                    if (Trigger.isExecuting) {
                        system.debug(authorPublisher);
                        authorPublisher.addError('You have to delete the associated books first');
                    }
                }
            }
        }
        this.setResponse(bookRecordsThatCauseError);
    }
}