force-app/main/default/objects/Author__c/Author__c.object-meta.xml
<CustomObject>
    <label>Author</label>
    <nameField>
        <displayFormat>AP-{0000}</displayFormat>
        <label>Author Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Authors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Standard_Authors_Settting__c/Standard_Authors_Settting__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Standard Authors Settting</label>
</CustomObject>

force-app/main/default/objects/Standard_Authors_Settting__c/fields/AnonymousId__c.field-meta.xml
<CustomField>
    <fullName>AnonymousId__c</fullName>
    <label>AnonymousId</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Standard_Authors_Settting__c/fields/UnknownId__c.field-meta.xml
<CustomField>
    <fullName>UnknownId__c</fullName>
    <label>UnknownId</label>
    <length>15</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/test/default/classes/unit/StandardAuthorCreatorTest.cls
/*
 * This class tests StandardAuthorCreator methods
 */
@isTest
public with sharing class StandardAuthorCreatorTest {

    @isTest
    public static void create_ifDontAlreadyExist_willCreateAuthorsAndCustomSettings(){
        //execute
        Test.startTest();
        StandardAuthorCreator.create();
        Test.stopTest();
        
        //assert custom setting creation
        List<Standard_Authors_Settting__c> stdAuthorSettings = Standard_Authors_Settting__c.getall().values();
        Assert.isTrue(stdAuthorSettings.size()==1, 'Custom settings were not created');

        //get corresponding authors and assert they have correct name field values
        Map<Id,Author__c> stdAuthors = new  Map<Id,Author__c>([
            SELECT
                Id,
                Name
            FROM
                Author__c
        ]);
        Assert.areEqual('Anonymous Author', stdAuthors.get(stdAuthorSettings[0].AnonymousId__c).Name, 'Anonymous Author not found or name invalid');
        Assert.areEqual('Unknown Author', stdAuthors.get(stdAuthorSettings[0].UnknownId__c).Name,'Unknown Author not found or name invalid');
    }

    @isTest
    public static void create_ifAlreadyCreated_willNotCreateNew(){
        //create pre-existing data
        StandardAuthorCreator.create();
        Assert.isTrue(Limits.getDMLStatements()==2, 'Two dml operations should have been ran');

        //execute and assert no insertions have ben made within test context
        Test.startTest();
        StandardAuthorCreator.create();
        Assert.isTrue(Limits.getDMLStatements()==0, 'No dml operations should have been ran');
        Test.stopTest();
    }
}