force-app/main/default/objects/Author__c/Author__c.object-meta.xml
<CustomObject>
    <label>Author</label>
    <nameField>
        <displayFormat>AP-{0000}</displayFormat>
        <label>Author Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Authors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Author_Publisher__c/Author_Publisher__c.object-meta.xml
<CustomObject>
    <label>Author_Publisher</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Author_Publisher Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Author_Publishers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Author_Publisher__c/fields/Author__c.field-meta.xml
<CustomField>
    <fullName>Author__c</fullName>
    <label>Author</label>
    <referenceTo>Author__c</referenceTo>
    <relationshipLabel>Author_Publishers</relationshipLabel>
    <relationshipName>Author_Publishers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Author_Publisher__c/fields/Publisher__c.field-meta.xml
<CustomField>
    <fullName>Publisher__c</fullName>
    <label>Publisher</label>
    <referenceTo>Publisher__c</referenceTo>
    <relationshipLabel>Author_Publishers</relationshipLabel>
    <relationshipName>Author_Publishers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Book__c/Book__c.object-meta.xml
<CustomObject>
    <label>Book</label>
    <nameField>
        <label>Book Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Books</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Book__c/fields/Author__c.field-meta.xml
<CustomField>
    <fullName>Author__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Author</label>
    <referenceTo>Author__c</referenceTo>
    <relationshipLabel>Books</relationshipLabel>
    <relationshipName>Books</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Book__c/fields/Publisher__c.field-meta.xml
<CustomField>
    <fullName>Publisher__c</fullName>
    <label>Publisher</label>
    <referenceTo>Publisher__c</referenceTo>
    <relationshipLabel>Books</relationshipLabel>
    <relationshipName>Books</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Publisher__c/Publisher__c.object-meta.xml
<CustomObject>
    <label>Publisher</label>
    <nameField>
        <label>Publisher Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Publishers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/test/default/classes/unit/ConverBookRestApiJsonDataServiceTest.cls
/**
 * Class used for testing ConvertBookRestApiJsonDataService
 */
@isTest
public with sharing class ConverBookRestApiJsonDataServiceTest {
    @isTest
    public static void convert_willReturnBookRestApiRequestDTOWithData_ifDataWasProvidedInJsonRequest() {
        // create data
        TestFactory testFactory = new TestFactory();
        Publisher__c publisherForTest = testFactory.createPublisher(true, false);
        Author__c authorForTest = testFactory.createAuthor(true, false);
        Author_Publisher__c authorPublisherForTest = testFactory.createAuthorPublisher(authorForTest.Id, publisherForTest.Id, true, false);
        Book__c book1 = testFactory.createBook(publisherForTest.Id, authorForTest.Id, false, false);
        Book__c book2 = testFactory.createBook(publisherForTest.Id, authorForTest.Id, false, false);

        Map<String, Object> jsonMap = new Map<String, Object>();
        jsonMap.put('data', new List<Book__c>{ book1, book2 });
        jsonMap.put('option', 1);
        
        // execute
        ConvertBookRestApiJsonDataService service = new ConvertBookRestApiJsonDataService();
        BookRestApiRequestDTO bookRestApiRequestDto = service.convert(JSON.serialize(jsonMap));

        // Assert
        Assert.areEqual(2, bookRestApiRequestDto.bookList.size());
        Assert.areEqual(1, bookRestApiRequestDto.insertOption);
    }

    @isTest
    public static void convert_willReturnBookRestApiRequestDTOWithoutData_ifDataWasntProvidedInJsonRequest() {
        // create data
        TestFactory testFactory = new TestFactory();
        Publisher__c publisherForTest = testFactory.createPublisher(true, false);
        Author__c authorForTest = testFactory.createAuthor(true, false);
        Author_Publisher__c authorPublisherForTest = testFactory.createAuthorPublisher(authorForTest.Id, publisherForTest.Id, true, false);
        Book__c book1 = testFactory.createBook(publisherForTest.Id, authorForTest.Id, false, false);
        Book__c book2 = testFactory.createBook(publisherForTest.Id, authorForTest.Id, false, false);
        Map<String, Object> jsonMap = new Map<String, Object>();
        
        // execute
        ConvertBookRestApiJsonDataService service = new ConvertBookRestApiJsonDataService();
        BookRestApiRequestDTO bookRestApiRequestDto = service.convert(JSON.serialize(jsonMap));

        // Assert
        Assert.areEqual(null, bookRestApiRequestDto.bookList);
        Assert.areEqual(null, bookRestApiRequestDto.insertOption);
    }
}