force-app/main/default/objects/Author__c/Author__c.object-meta.xml
<CustomObject>
    <label>Author</label>
    <nameField>
        <displayFormat>AP-{0000}</displayFormat>
        <label>Author Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Authors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Book__c/Book__c.object-meta.xml
<CustomObject>
    <label>Book</label>
    <nameField>
        <label>Book Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Books</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Book__c/fields/Author__c.field-meta.xml
<CustomField>
    <fullName>Author__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Author</label>
    <referenceTo>Author__c</referenceTo>
    <relationshipLabel>Books</relationshipLabel>
    <relationshipName>Books</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Book__c/fields/Publisher__c.field-meta.xml
<CustomField>
    <fullName>Publisher__c</fullName>
    <label>Publisher</label>
    <referenceTo>Publisher__c</referenceTo>
    <relationshipLabel>Books</relationshipLabel>
    <relationshipName>Books</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Bookstore__c/Bookstore__c.object-meta.xml
<CustomObject>
    <label>Bookstore</label>
    <nameField>
        <label>Bookstore Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookstores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Publisher__c/Publisher__c.object-meta.xml
<CustomObject>
    <label>Publisher</label>
    <nameField>
        <label>Publisher Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Publishers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/test/default/classes/unit/GetDigitalBooksServiceTest.cls
/*
 * Class used for testing GetDigitalBooksService, will perform 1 positive, 1 negative and 1 method execution test
 */
@isTest
public with sharing class GetDigitalBooksServiceTest {
    @isTest
    public static void getBooks_willReturnOneBook_ifOneDigitalBookIsCreated() {
        // create data
        TestFactory testFactory = new TestFactory();
        Publisher__c publisherForTest = testFactory.createPublisher(false, true);
        Bookstore__c bookstoreForTest = testFactory.createBookstore(false, true);
        Author__c authorForTest = testFactory.createAuthor(true, false);
        Book__c bookForTest = testFactory.createDigitalBook(publisherForTest.Id, authorForTest.Id, false, true);
        
        // create mock
        Mocker BookSelectorMock = new Mocker(BookSelector.class)
        .setBehavior('getDigitalBooksList', new List<Book__c>{bookForTest});
        ObjectFactory.mocks.put(
            BookSelector.class.getName(),
            (BookSelector)BookSelectorMock.getMock()
        );

        // execute
        GetDigitalBooksService service = new GetDigitalBooksService();
        service.getBooks('');
        List<Book__c> booksNotInBookstore = service.getResponse();

        // assert
        Assert.areEqual(1, booksNotInBookstore.size());
    }

    @isTest
    public static void getBooks_willNotReturnAnything_ifNoDigitalBooksWereCreated() {
        // create  mock
        Mocker BookSelectorMock = new Mocker(BookSelector.class)
        .setBehavior('getDigitalBooksList', new List<Book__c>{});
        ObjectFactory.mocks.put(
            BookSelector.class.getName(),
            (BookSelector)BookSelectorMock.getMock()
        );

        // execute
        GetDigitalBooksService service = new GetDigitalBooksService();
        service.getBooks('');
        List<Book__c> booksNotInBookstore = service.getResponse();

        // assert
        Assert.areEqual(0, booksNotInBookstore.size());
    }

    @isTest
    public static void getBooks_willUseCorrectSelector() {
        // create  mock
        Mocker BookSelectorMock = new Mocker(BookSelector.class)
        .setBehavior('getDigitalBooksList', new List<Book__c>{});
        ObjectFactory.mocks.put(
            BookSelector.class.getName(),
            (BookSelector)BookSelectorMock.getMock()
        );

        // execute
        GetDigitalBooksService service = new GetDigitalBooksService();
        service.getBooks('');
        List<Book__c> booksNotInBookstore = service.getResponse();

        // assert
        BookSelectorMock.assertMethodExecutionCount('getDigitalBooksList', 1);
    }
}