force-app/main/default/objects/Author__c/Author__c.object-meta.xml
<CustomObject>
    <label>Author</label>
    <nameField>
        <displayFormat>AP-{0000}</displayFormat>
        <label>Author Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Authors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Author__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <description>Author&apos;s first name.</description>
    <label>First Name</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Author__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <description>Authors last name.</description>
    <label>Last Name</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Standard_Authors_Settting__c/Standard_Authors_Settting__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Standard Authors Settting</label>
</CustomObject>

force-app/main/default/objects/Standard_Authors_Settting__c/fields/AnonymousId__c.field-meta.xml
<CustomField>
    <fullName>AnonymousId__c</fullName>
    <label>AnonymousId</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Standard_Authors_Settting__c/fields/UnknownId__c.field-meta.xml
<CustomField>
    <fullName>UnknownId__c</fullName>
    <label>UnknownId</label>
    <length>15</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AdminScript/StandardAuthorCreator.cls
/*
 * This class automaticaly creates the Anonymous and Unknown out-of-the box Author__c sObjects
 * stopTrigger variable serves for disabling trigger during test
 */
global with sharing class StandardAuthorCreator {
//method for creation
//sets ids to custom metadata
//in trigger checking if the ids match
    public static void create(){
        List<Standard_Authors_Settting__c> stdAuthorSettings = Standard_Authors_Settting__c.getall().values();

        if (stdAuthorSettings.size()>0) {
            return;
        }
        List<Author__c> authorsToCreate = new List<Author__c>();
        Author__c anonymousAuthor = new Author__c(First_Name__c='Anonymous', Last_Name__c='Author');
        authorsToCreate.add(anonymousAuthor);
        Author__c unknownAuthor = new Author__c(First_Name__c='Unknown', Last_Name__c='Author');
        authorsToCreate.add(unknownAuthor);
        insert authorsToCreate;

        Standard_Authors_Settting__c stdAuthorSettingForInsert = new Standard_Authors_Settting__c();
        stdAuthorSettingForInsert.AnonymousId__c=anonymousAuthor.Id;
        stdAuthorSettingForInsert.UnknownId__c=unknownAuthor.Id;
        insert stdAuthorSettingForInsert;
    }
}