force-app/main/default/objects/Author__c/Author__c.object-meta.xml
<CustomObject>
    <label>Author</label>
    <nameField>
        <displayFormat>AP-{0000}</displayFormat>
        <label>Author Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Authors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Author_Publisher__c/Author_Publisher__c.object-meta.xml
<CustomObject>
    <label>Author_Publisher</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Author_Publisher Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Author_Publishers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Author_Publisher__c/fields/Author__c.field-meta.xml
<CustomField>
    <fullName>Author__c</fullName>
    <label>Author</label>
    <referenceTo>Author__c</referenceTo>
    <relationshipLabel>Author_Publishers</relationshipLabel>
    <relationshipName>Author_Publishers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Author_Publisher__c/fields/Publisher__c.field-meta.xml
<CustomField>
    <fullName>Publisher__c</fullName>
    <label>Publisher</label>
    <referenceTo>Publisher__c</referenceTo>
    <relationshipLabel>Author_Publishers</relationshipLabel>
    <relationshipName>Author_Publishers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Bookstore__c/Bookstore__c.object-meta.xml
<CustomObject>
    <label>Bookstore</label>
    <nameField>
        <label>Bookstore Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookstores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Bookstore_Publisher__c/Bookstore_Publisher__c.object-meta.xml
<CustomObject>
    <label>Bookstore_Publisher</label>
    <nameField>
        <displayFormat>BP-{0000}</displayFormat>
        <label>Bookstore Publisher Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookstore Publishers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bookstore_Publisher__c/fields/Bookstore__c.field-meta.xml
<CustomField>
    <fullName>Bookstore__c</fullName>
    <label>Bookstore</label>
    <referenceTo>Bookstore__c</referenceTo>
    <relationshipName>Bookstore_Publishers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Bookstore_Publisher__c/fields/Publisher__c.field-meta.xml
<CustomField>
    <fullName>Publisher__c</fullName>
    <label>Publisher</label>
    <referenceTo>Publisher__c</referenceTo>
    <relationshipName>Bookstore_Publishers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Publisher__c/Publisher__c.object-meta.xml
<CustomObject>
    <label>Publisher</label>
    <nameField>
        <label>Publisher Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Publishers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/test/default/classes/unit/PageReferenceServiceTest.cls
/**
 * Class used for testing GetPageReferenceForBookstorePublsherService
 */
@isTest
public with sharing class PageReferenceServiceTest {
    @isTest
    public static void getPageReferenceForBookstorePublisher_willReturnPageRef_ifIsCanceledIsTrue() {
        // create data
        TestFactory testFactory = new TestFactory();
        Publisher__c publisherForTest = testFactory.createPublisher(true);
        Bookstore__c bookstoreForTest = testFactory.createBookstore(true);
        Bookstore_Publisher__c bookstorePublisherForTest = testFactory
            .createBookstorePublisher(publisherForTest.Id, bookstoreForTest.Id, true);

        // execute
        PageReferenceService service = new PageReferenceService();
        service.getPageReferenceForBookstorePublisher(true, false, false, bookstorePublisherForTest);

        // Assert
        Assert.isTrue(service.getResponse() != null);
        Assert.areEqual(service.getResponse().getUrl(), '/' + bookstoreForTest.Id);
    }

    @isTest
    public static void getPageReferenceForBookstorePublisher_willReturnPageRef_ifDeleteStatusIsFalse() {
        // create data
        TestFactory testFactory = new TestFactory();
        Publisher__c publisherForTest = testFactory.createPublisher(true);
        Bookstore__c bookstoreForTest = testFactory.createBookstore(true);
        Bookstore_Publisher__c bookstorePublisherForTest = testFactory
            .createBookstorePublisher(publisherForTest.Id, bookstoreForTest.Id, true);

        // execute
        PageReferenceService service = new PageReferenceService();
        service.getPageReferenceForBookstorePublisher(false, false, false, bookstorePublisherForTest);

        // Assert
        Assert.isTrue(service.getResponse() != null);
        Assert.areEqual(service.getResponse().getUrl(), '/' + bookstoreForTest.Id);
    }

    @isTest
    public static void getPageReferenceForBookstorePublisher_willReturnPageRef_ifviewAllIsClicked() {
        // create data
        TestFactory testFactory = new TestFactory();
        Publisher__c publisherForTest = testFactory.createPublisher(true);
        Bookstore__c bookstoreForTest = testFactory.createBookstore(true);
        Bookstore_Publisher__c bookstorePublisherForTest = testFactory
            .createBookstorePublisher(publisherForTest.Id, bookstoreForTest.Id, true);

        // execute
        PageReferenceService service = new PageReferenceService();
        service.getPageReferenceForBookstorePublisher(false, true, true, bookstorePublisherForTest);

        // Assert
        Assert.isTrue(service.getResponse() != null);
        Assert.areEqual(service.getResponse().getUrl(), '/lightning/n/Books_preventing_publisher_removal?c__recordId=' + bookstorePublisherForTest.Id);
    }

    @isTest
    public static void getPageReferenceForBookstorePublisher_willReturnNull_ifNoButtonsWereClickedAndDeleteStatusIsTrue() {
        // create data
        TestFactory testFactory = new TestFactory();
        Publisher__c publisherForTest = testFactory.createPublisher(true);
        Bookstore__c bookstoreForTest = testFactory.createBookstore(true);
        Bookstore_Publisher__c bookstorePublisherForTest = testFactory
            .createBookstorePublisher(publisherForTest.Id, bookstoreForTest.Id, true);
    
        // execute
        PageReferenceService service = new PageReferenceService();
        service.getPageReferenceForBookstorePublisher(false, false, true, bookstorePublisherForTest);

        // Assert
        Assert.isTrue(service.getResponse() == null);
    }

    @isTest
    public static void getPageReferenceForAuthorPublisher_willReturnPageRef_ifIsCanceledIsTrue() {
        // create data
        TestFactory testFactory = new TestFactory();
        Publisher__c publisherForTest = testFactory.createPublisher(true);
        Author__c authorForTest = testFactory.createAuthor(true);
        Author_Publisher__c authorPublisherForTest = testFactory
            .createAuthorPublisher(authorForTest.Id, authorForTest.Id, true);

        // execute
        PageReferenceService service = new PageReferenceService();
        service.getPageReferenceForAuthorPublisher(true, false, false, authorPublisherForTest);

        // Assert
        Assert.isTrue(service.getResponse() != null);
        Assert.areEqual(service.getResponse().getUrl(), '/' + authorForTest.Id);
    }

    @isTest
    public static void getPageReferenceForAuthorPublisher_willReturnPageRef_ifDeleteStatusIsFalse() {
        // create data
        TestFactory testFactory = new TestFactory();
        Publisher__c publisherForTest = testFactory.createPublisher(true);
        Author__c authorForTest = testFactory.createAuthor(true);
        Author_Publisher__c authorPublisherForTest = testFactory
            .createAuthorPublisher(publisherForTest.Id, authorForTest.Id, true);

        // execute
        PageReferenceService service = new PageReferenceService();
        service.getPageReferenceForAuthorPublisher(false, false, false, authorPublisherForTest);

        // Assert
        Assert.isTrue(service.getResponse() != null);
        Assert.areEqual(service.getResponse().getUrl(), '/' + authorForTest.Id);
    }

    @isTest
    public static void getPageReferenceForAuthorPublisher_willReturnPageRef_ifviewAllIsClicked() {
        // create data
        TestFactory testFactory = new TestFactory();
        Publisher__c publisherForTest = testFactory.createPublisher(true);
        Author__c authorForTest = testFactory.createAuthor(true);
        Author_Publisher__c authorPublisherForTest = testFactory
            .createAuthorPublisher(publisherForTest.Id, authorForTest.Id, true);

        // execute
        PageReferenceService service = new PageReferenceService();
        service.getPageReferenceForAuthorPublisher(false, true, true, authorPublisherForTest);

        // Assert
        Assert.isTrue(service.getResponse() != null);
        Assert.areEqual(service.getResponse().getUrl(), '/lightning/n/Books_preventing_author_removal?c__recordId=' + authorPublisherForTest.Id);
    }

    @isTest
    public static void getPageReferenceForAuthorPublisher_willReturnNull_ifNoButtonsWereClickedAndDeleteStatusIsTrue() {
        // create data
        TestFactory testFactory = new TestFactory();
        Publisher__c publisherForTest = testFactory.createPublisher(true);
        Author__c authorForTest = testFactory.createAuthor(true);
        Author_Publisher__c authorPublisherForTest = testFactory
            .createAuthorPublisher(publisherForTest.Id, authorForTest.Id, true);
    
        // execute
        PageReferenceService service = new PageReferenceService();
        service.getPageReferenceForAuthorPublisher(false, false, true, authorPublisherForTest);

        // Assert
        Assert.isTrue(service.getResponse() == null);
    }
}