force-app/main/default/objects/Author__c/Author__c.object-meta.xml
<CustomObject>
    <label>Author</label>
    <nameField>
        <displayFormat>AP-{0000}</displayFormat>
        <label>Author Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Authors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Book__c/Book__c.object-meta.xml
<CustomObject>
    <label>Book</label>
    <nameField>
        <label>Book Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Books</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Book__c/fields/Author__c.field-meta.xml
<CustomField>
    <fullName>Author__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Author</label>
    <referenceTo>Author__c</referenceTo>
    <relationshipLabel>Books</relationshipLabel>
    <relationshipName>Books</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Book__c/fields/Publisher__c.field-meta.xml
<CustomField>
    <fullName>Publisher__c</fullName>
    <label>Publisher</label>
    <referenceTo>Publisher__c</referenceTo>
    <relationshipLabel>Books</relationshipLabel>
    <relationshipName>Books</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Bookstore__c/Bookstore__c.object-meta.xml
<CustomObject>
    <label>Bookstore</label>
    <nameField>
        <label>Bookstore Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookstores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Bookstore_Book__c/Bookstore_Book__c.object-meta.xml
<CustomObject>
    <label>Bookstore_Book</label>
    <nameField>
        <label>Bookstore_Book Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookstore_Books</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bookstore_Book__c/fields/Book__c.field-meta.xml
<CustomField>
    <fullName>Book__c</fullName>
    <label>Book</label>
    <referenceTo>Book__c</referenceTo>
    <relationshipLabel>Bookstore Books</relationshipLabel>
    <relationshipName>Bookstore_Books</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Bookstore_Book__c/fields/Bookstore__c.field-meta.xml
<CustomField>
    <fullName>Bookstore__c</fullName>
    <label>Bookstore</label>
    <referenceTo>Bookstore__c</referenceTo>
    <relationshipLabel>Bookstore Books</relationshipLabel>
    <relationshipName>Bookstore_Books</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Publisher__c/Publisher__c.object-meta.xml
<CustomObject>
    <label>Publisher</label>
    <nameField>
        <label>Publisher Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Publishers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/test/default/classes/integration/ControllerIntegrationTest.cls
/**
 * This class performs integration tests on controller methods
 * 
 * @see AuthorController.cls
 */
@isTest
public with sharing class ControllerIntegrationTest {
    @IsTest
    static void getBookstoresWithAuthorsBooks_WillReturnNull_IfNullPassed() {
        // execute
        Test.startTest();
        List<Bookstore__c> bookstores = AuthorController.getBookstoresWithAuthorsBooks(null);
        Test.stopTest();

        // assert
        Assert.areEqual(null, bookstores);
    }
    
    @IsTest
    static void getBookstoresWithAuthorsBooks_WillReturnEmptyList_IfNoBookstoresAreFound() {
        // create testFactory
        TestFactory testFactory = new TestFactory();

        //create and insert Author__c object
        Author__c author = testFactory.createAuthor(true, false);

        // execute
        Test.startTest();
        List<Bookstore__c> bookstores = AuthorController.getBookstoresWithAuthorsBooks(author.Id);
        Test.stopTest();

        // assert
        Assert.areEqual(0, bookstores.size());
    }

    @IsTest
    static void getBookstoresWithAuthorsBooks_WillReturnBookstoresWithAuthorsBooks_IfAtLeastOneIsFound() {
        // create testFactory
        TestFactory testFactory = new TestFactory();

        //create and insert Author__c object
        Author__c author = testFactory.createAuthor(true, false);

        // create and insert Publisher__c object
        Publisher__c publisher = testFactory.createPublisher(true, false);

        //create and insert Book__c object
        Book__c book = testFactory.createBook(publisher.Id, author.Id, true, false);

        //create and insert Bookstore__c object
        Bookstore__c bookstore = testFactory.createBookstore(true, false);

        //create and insert Bookstore_Book__c junction object
        Bookstore_Book__c bookstoreBook = testFactory.createBookstoreBook(book.Id, bookstore.Id, true, false);

        // execute
        Test.startTest();
        List<Bookstore__c> bookstores = AuthorController.getBookstoresWithAuthorsBooks(author.Id);
        Test.stopTest();

        // assert
        Assert.areEqual(1, bookstores.size());
        Assert.areEqual(bookstore.Id, bookstores[0].Id);
    }

    @IsTest
    static void getBookstoresWithAuthorsBooks_WillReturnThreeBookstoresWithAuthorsBooks_IfThereAreThreeBookstoresWithAuthorsBooks() {
        // create testFactory
        TestFactory testFactory = new TestFactory();

        //create and insert Author__c object
        Author__c author = testFactory.createAuthor(true, false);

        // create and insert Publisher__c object
        Publisher__c publisher = testFactory.createPublisher(true, false);

        //create and insert Book__c object
        Book__c book = testFactory.createBook(publisher.Id, author.Id, true, false);

        //create and insert Bookstore__c objects
        Bookstore__c bookstore1 = testFactory.createBookstore(true, false);

        //We need to change the unique store Id number, Name and Email
        // before inserting another bookstore
        testFactory.bookstoreDetails.put('name', 'bookstore2');
        testFactory.bookstoreDetails.put('email', 'bookstore2@gmail.com');
        testFactory.bookstoreDetails.put('storeId', '85758498');
        Bookstore__c bookstore2 = testFactory.createBookstore(true, false);

        //We need to change the unique store Id number, Name and Email
        // before inserting another bookstore
        testFactory.bookstoreDetails.put('name', 'bookstore3');
        testFactory.bookstoreDetails.put('email', 'bookstore3@gmail.com');
        testFactory.bookstoreDetails.put('storeId', '04793211');
        Bookstore__c bookstore3 = testFactory.createBookstore(true, false);

        //create and insert Bookstore_Book__c junction objects
        Bookstore_Book__c bookstoreBook1 = testFactory.createBookstoreBook(book.Id, bookstore1.Id, true, false);
        Bookstore_Book__c bookstoreBook2 = testFactory.createBookstoreBook(book.Id, bookstore2.Id, true, false);
        Bookstore_Book__c bookstoreBook3 = testFactory.createBookstoreBook(book.Id, bookstore3.Id, true, false);

        // execute
        Test.startTest();
        List<Bookstore__c> bookstores = AuthorController.getBookstoresWithAuthorsBooks(author.Id);
        Test.stopTest();

        // assert
        Assert.areEqual(3, bookstores.size());
        Assert.areEqual(bookstore1.Id, bookstores[0].Id);
        Assert.areEqual(bookstore2.Id, bookstores[1].Id);
        Assert.areEqual(bookstore3.Id, bookstores[2].Id);
    }
}