force-app/main/default/objects/Author__c/Author__c.object-meta.xml
<CustomObject>
    <label>Author</label>
    <nameField>
        <displayFormat>AP-{0000}</displayFormat>
        <label>Author Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Authors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Book__c/Book__c.object-meta.xml
<CustomObject>
    <label>Book</label>
    <nameField>
        <label>Book Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Books</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Book__c/fields/Author__c.field-meta.xml
<CustomField>
    <fullName>Author__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Author</label>
    <referenceTo>Author__c</referenceTo>
    <relationshipLabel>Books</relationshipLabel>
    <relationshipName>Books</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Book__c/fields/Publisher__c.field-meta.xml
<CustomField>
    <fullName>Publisher__c</fullName>
    <label>Publisher</label>
    <referenceTo>Publisher__c</referenceTo>
    <relationshipLabel>Books</relationshipLabel>
    <relationshipName>Books</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Bookstore__c/Bookstore__c.object-meta.xml
<CustomObject>
    <label>Bookstore</label>
    <nameField>
        <label>Bookstore Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookstores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Bookstore_Book__c/Bookstore_Book__c.object-meta.xml
<CustomObject>
    <label>Bookstore_Book</label>
    <nameField>
        <label>Bookstore_Book Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookstore_Books</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bookstore_Book__c/fields/Book__c.field-meta.xml
<CustomField>
    <fullName>Book__c</fullName>
    <label>Book</label>
    <referenceTo>Book__c</referenceTo>
    <relationshipLabel>Bookstore Books</relationshipLabel>
    <relationshipName>Bookstore_Books</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Bookstore_Book__c/fields/Bookstore__c.field-meta.xml
<CustomField>
    <fullName>Bookstore__c</fullName>
    <label>Bookstore</label>
    <referenceTo>Bookstore__c</referenceTo>
    <relationshipLabel>Bookstore Books</relationshipLabel>
    <relationshipName>Bookstore_Books</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Bookstore_Publisher__c/Bookstore_Publisher__c.object-meta.xml
<CustomObject>
    <label>Bookstore_Publisher</label>
    <nameField>
        <displayFormat>BP-{0000}</displayFormat>
        <label>Bookstore Publisher Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookstore Publishers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bookstore_Publisher__c/fields/Bookstore__c.field-meta.xml
<CustomField>
    <fullName>Bookstore__c</fullName>
    <label>Bookstore</label>
    <referenceTo>Bookstore__c</referenceTo>
    <relationshipName>Bookstore_Publishers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Bookstore_Publisher__c/fields/Publisher__c.field-meta.xml
<CustomField>
    <fullName>Publisher__c</fullName>
    <label>Publisher</label>
    <referenceTo>Publisher__c</referenceTo>
    <relationshipName>Bookstore_Publishers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Publisher__c/Publisher__c.object-meta.xml
<CustomObject>
    <label>Publisher</label>
    <nameField>
        <label>Publisher Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Publishers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/test/default/classes/unit/BookSearchServiceTest.cls
/*
 * This class is used for testing book search service
 * There will be 1 positive, 2 negative and 2 mockerexecutioncount tests
 */
@IsTest
public with sharing class BookSearchServiceTest {
    @IsTest
    static void getBooksFromSearchDTO_IfReviewScoreSet_WillUseBothSelectors() {
        // create mock
        Mocker bookSelectorMock = new Mocker(BookSelector.class)
            .setBehavior('getListFromQueryConditions', new List<Book__c>{});
        // set mock
        ObjectFactory.mocks.put(
            BookSelector.class.getName(),
            (BookSelector) bookSelectorMock.getMock()
        );

        //create mock
        Mocker bookReviewSelectorMock = new Mocker(BookReviewSelector.class)
            .setBehavior('getAverageRatingListByBookIdSet', new List<AggregateResult>{});
        // set mock
        ObjectFactory.mocks.put(
            BookReviewSelector.class.getName(),
            (BookReviewSelector) bookReviewSelectorMock.getMock()
        );

        //create data
        BookSearchDTO bookDTO = new TestFactory().createBookSearchDTO(null, null, null);

        // execute
        Test.startTest();
        BookSearchService service = new BookSearchService();
        service.getBooksFromSearchDTO(bookDTO, 1, 1 );
        List<Book__c> books = service.getResponse();
        Test.stopTest();

        // assert
        bookSelectorMock.assertMethodExecutionCount('getListFromQueryConditions', 1);
        bookReviewSelectorMock.assertMethodExecutionCount('getAverageRatingListByBookIdSet', 1);
    }

    @IsTest
    static void getBooksFromSearchDTO_IfReviewScoreNotSet_WillNotUseReviewSelector() {
        // create mock
        Mocker bookSelectorMock = new Mocker(BookSelector.class)
            .setBehavior('getListFromQueryConditions', new List<Book__c>{});
        // set mock
        ObjectFactory.mocks.put(
            BookSelector.class.getName(),
            (BookSelector) bookSelectorMock.getMock()
        );

        //create mock
        Mocker bookReviewSelectorMock = new Mocker(BookReviewSelector.class)
            .setBehavior('getAverageRatingListByBookIdSet', new List<AggregateResult>{});
        // set mock
        ObjectFactory.mocks.put(
            BookReviewSelector.class.getName(),
            (BookReviewSelector) bookReviewSelectorMock.getMock()
        );

        // execute
        Test.startTest();
        BookSearchService service = new BookSearchService();
        service.getBooksFromSearchDTO(new BookSearchDTO(), 1, 1 );
        List<Book__c> books = service.getResponse();
        Test.stopTest();

        // assert
        bookSelectorMock.assertMethodExecutionCount('getListFromQueryConditions', 1);
        bookReviewSelectorMock.assertMethodExecutionCount('getAverageRatingListByBookIdSet', 0);
    }

    @IsTest
    static void getBooksFromSearchDTO_IfBookSearchDTONull_WillSetResponseToNull() {
        // create mock
        Mocker bookSelectorMock = new Mocker(BookSelector.class)
            .setBehavior('getListFromQueryConditions', new List<Book__c>{});
        // set mock
        ObjectFactory.mocks.put(
            BookSelector.class.getName(),
            (BookSelector) bookSelectorMock.getMock()
        );

        //create mock
        Mocker bookReviewSelectorMock = new Mocker(BookReviewSelector.class)
            .setBehavior('getAverageRatingListByBookIdSet', new List<AggregateResult>{});
        // set mock
        ObjectFactory.mocks.put(
            BookReviewSelector.class.getName(),
            (BookReviewSelector) bookReviewSelectorMock.getMock()
        );

        // execute
        Test.startTest();
        BookSearchService service = new BookSearchService();
        service.getBooksFromSearchDTO(null, 1, 1 );
        List<Book__c> books = service.getResponse();
        Test.stopTest();

        // assert
        Assert.areEqual(null, books, 'Service should have null response value');
    }

    @IsTest
    static void getBooksFromSearchDTO_IfAllSearchParametersSetAndNoMatches_WillSetResponseToEmptyBookList() {
        // create testFactory
        TestFactory testFactory = new TestFactory();

        //create and insert Author__c object
        Author__c author = testFactory.createAuthor(false, true);

        // create and insert Publisher__c object
        Publisher__c publisher = testFactory.createPublisher(false, true);

        //create and insert Book__c object
        Book__c book = testFactory.createBook(publisher.Id, author.Id, false, true);

        //create and insert Bookstore__c objects
        Bookstore__c bookstore = testFactory.createBookstore(false, true);

        //create Bookstore_Publisher__c junction object
        Bookstore_Publisher__c bookstorePublisher = testFactory.createBookstorePublisher(publisher.Id, bookstore.Id, false, true);

        //create Bookstore_Book__c junction object
        Bookstore_Book__c bookstoreBook = testFactory.createBookstoreBook(book.Id, bookstore.Id, false, true);

        //create BookSearchDTO
        BookSearchDTO bookDTO = new TestFactory().createBookSearchDTO(author.Id, publisher.Id, bookstore.Id);

        // create mock
        Mocker bookSelectorMock = new Mocker(BookSelector.class)
            .setBehavior('getListFromQueryConditions', new List<Book__c>{book});
        // set mock
        ObjectFactory.mocks.put(
            BookSelector.class.getName(),
            (BookSelector) bookSelectorMock.getMock()
        );

        //create mock
        Mocker bookReviewSelectorMock = new Mocker(BookReviewSelector.class)
            .setBehavior('getAverageRatingListByBookIdSet', new List<AggregateResult>{});
        // set mock
        ObjectFactory.mocks.put(
            BookReviewSelector.class.getName(),
            (BookReviewSelector) bookReviewSelectorMock.getMock()
        );

        // execute
        Test.startTest();
        BookSearchService service = new BookSearchService();
        service.getBooksFromSearchDTO(bookDTO, 1, 1 );
        List<Book__c> books = service.getResponse();
        Test.stopTest();

        // assert
        Assert.areEqual(0, books.size(), 'The response book list should be empty as no matches were found');
    }

    @IsTest
    static void getBooksFromSearchDTO_IfSearchParametersPartiallySetAndMatch_WillSetResponseToMatchingBookList() {
        // create testFactory
        TestFactory testFactory = new TestFactory();

        //create and insert Author__c object
        Author__c author = testFactory.createAuthor(false, true);

        // create and insert Publisher__c object
        Publisher__c publisher = testFactory.createPublisher(false, true);

        //create and insert Book__c object
        Book__c book = testFactory.createBook(publisher.Id, author.Id, false, true);

        //create and insert Bookstore__c objects
        Bookstore__c bookstore = testFactory.createBookstore(false, true);

        //create Bookstore_Publisher__c junction object
        Bookstore_Publisher__c bookstorePublisher = testFactory.createBookstorePublisher(publisher.Id, bookstore.Id, false, true);

        //create Bookstore_Book__c junction object
        Bookstore_Book__c bookstoreBook = testFactory.createBookstoreBook(book.Id, bookstore.Id, false, true);

        //create BookSearchDTO, reset name and reviewScore to null
        BookSearchDTO bookDTO = new TestFactory().createBookSearchDTO(author.Id, publisher.Id, bookstore.Id);
        bookDTO.name=null;
        bookDTO.reviewScore=null;

        // create mock
        Mocker bookSelectorMock = new Mocker(BookSelector.class)
            .setBehavior('getListFromQueryConditions', new List<Book__c>{book});
        // set mock
        ObjectFactory.mocks.put(
            BookSelector.class.getName(),
            (BookSelector) bookSelectorMock.getMock()
        );

        //create mock
        Mocker bookReviewSelectorMock = new Mocker(BookReviewSelector.class)
            .setBehavior('getAverageRatingListByBookIdSet', new List<AggregateResult>{});
        // set mock
        ObjectFactory.mocks.put(
            BookReviewSelector.class.getName(),
            (BookReviewSelector) bookReviewSelectorMock.getMock()
        );

        // execute
        Test.startTest();
        BookSearchService service = new BookSearchService();
        service.getBooksFromSearchDTO(bookDTO, null, null );
        List<Book__c> books = service.getResponse();
        Test.stopTest();

        // assert
        Assert.areEqual(1, books.size(), 'The response book list should contain a single match');
        Assert.areEqual(book, books[0], 'Incorrect record added to the list');
    }
}