force-app/main/default/objects/Author__c/Author__c.object-meta.xml
<CustomObject>
    <label>Author</label>
    <nameField>
        <displayFormat>AP-{0000}</displayFormat>
        <label>Author Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Authors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Standard_Authors_Settting__c/Standard_Authors_Settting__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Standard Authors Settting</label>
</CustomObject>

force-app/main/default/objects/Standard_Authors_Settting__c/fields/AnonymousId__c.field-meta.xml
<CustomField>
    <fullName>AnonymousId__c</fullName>
    <label>AnonymousId</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Standard_Authors_Settting__c/fields/UnknownId__c.field-meta.xml
<CustomField>
    <fullName>UnknownId__c</fullName>
    <label>UnknownId</label>
    <length>15</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Service/AuthorDeleteValidationService.cls
/*
 * Class used to validate weather delete of standard Author__c records (Unknown, Anonymous) has been attempted
 * If they are found among the deleted records, the validation will result in an error
 */
public with sharing class AuthorDeleteValidationService implements CustomObject{
    /*
     * @param oldAuthors - Author__c records before delete
     */
    public void validateAuthorDelete(List<Author__c> oldAuthors){
        //get all records of Standard_Authors_Settting__c type 
        CustomSettingSelector customSettingSelector = (CustomSettingSelector) new ObjectFactory()
            .createObject(CustomSettingSelector.class);
        List<Standard_Authors_Settting__c> stdAuthorSettings = customSettingSelector.getStdAuthorsSettingList();

        //if list is empty (no out-of-the box authors have been created), return
        if (stdAuthorSettings.size() == 0) {
            return;
        }

        //search for record ids that match out-of-the box author ids among changed records
        for (Author__c oldAuthor : oldAuthors){
            //if matching records are found, add an error to them
            if (oldAuthor.Id == stdAuthorSettings[0].AnonymousId__c || oldAuthor.Id == stdAuthorSettings[0].UnknownId__c){
                oldAuthor.addError('Out-of-the-box authors (Unknown, Anonymous) cannot be deleted');
            }
        }
    }
}