force-app/main/default/objects/Author__c/Author__c.object-meta.xml
<CustomObject>
    <label>Author</label>
    <nameField>
        <displayFormat>AP-{0000}</displayFormat>
        <label>Author Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Authors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Book__c/Book__c.object-meta.xml
<CustomObject>
    <label>Book</label>
    <nameField>
        <label>Book Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Books</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Book__c/fields/Author__c.field-meta.xml
<CustomField>
    <fullName>Author__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Author</label>
    <referenceTo>Author__c</referenceTo>
    <relationshipLabel>Books</relationshipLabel>
    <relationshipName>Books</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Book__c/fields/Publisher__c.field-meta.xml
<CustomField>
    <fullName>Publisher__c</fullName>
    <label>Publisher</label>
    <referenceTo>Publisher__c</referenceTo>
    <relationshipLabel>Books</relationshipLabel>
    <relationshipName>Books</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Publisher__c/Publisher__c.object-meta.xml
<CustomObject>
    <label>Publisher</label>
    <nameField>
        <label>Publisher Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Publishers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/test/default/classes/unit/GetDuplicateBooksServiceTest.cls
/**
 * Class used for performing unit tests for GetDuplicateBooksService
 */
@isTest
public with sharing class GetDuplicateBooksServiceTest {
    @isTest
    public static void getDuplicates_willReturnDuplicates_ifDuplicatesExistInListProvidedAndDatabase() {
        // create data
        TestFactory testFactory = new TestFactory();
        Publisher__c publisherForTest = testFactory.createPublisher(true);
        Author__c authorForTest = testFactory.createAuthor(true);
        Book__c bookForTest = testFactory.createBook(publisherForTest.Id, authorForTest.Id, false);
        List<Book__c> bookListForTest = new List<Book__c>{ bookForTest, bookForTest };

        // create mock
        Mocker bookSelectorMocker = new Mocker(BookSelector.class)
            .setBehavior('getListByISBNs', new List<Book__c>{ bookForTest });
        ObjectFactory.mocks.put(
            BookSelector.class.getName(),
            (BookSelector) bookSelectorMocker.getMock()
        );

        // execute
        GetDuplicateBooksService service = new GetDuplicateBooksService();
        Map<String, List<Book__c>> duplicateLists = service.getDuplicates(bookListForTest);

        // assert
        Assert.areEqual(0, duplicateLists.get('nonDuplicateRecords').size());
        Assert.areEqual(3, duplicateLists.get('duplicateRecords').size());
        Assert.areEqual(1, duplicateLists.get('duplicatesFromDatabase').size());
    }

    @isTest
    public static void getDuplicates_willNotReturnDuplicates_ifDuplicatesDontExist() {
        // create data
        TestFactory testFactory = new TestFactory();
        Publisher__c publisherForTest = testFactory.createPublisher(true);
        Author__c authorForTest = testFactory.createAuthor(true);
        Book__c bookForTest = testFactory.createBook(publisherForTest.Id, authorForTest.Id, false);
        List<Book__c> bookListForTest = new List<Book__c>{ bookForTest };

        // create mock
        Mocker bookSelectorMocker = new Mocker(BookSelector.class)
            .setBehavior('getListByISBNs', new List<Book__c>{});
        ObjectFactory.mocks.put(
            BookSelector.class.getName(),
            (BookSelector) bookSelectorMocker.getMock()
        );

        // execute
        GetDuplicateBooksService service = new GetDuplicateBooksService();
        Map<String, List<Book__c>> duplicateLists = service.getDuplicates(bookListForTest);

        // assert
        Assert.areEqual(1, duplicateLists.get('nonDuplicateRecords').size());
        Assert.areEqual(0, duplicateLists.get('duplicateRecords').size());
        Assert.areEqual(0, duplicateLists.get('duplicatesFromDatabase').size());
    }

    @isTest
    public static void getDuplicates_willUseSelector() {
        // create data
        TestFactory testFactory = new TestFactory();
        Publisher__c publisherForTest = testFactory.createPublisher(true);
        Author__c authorForTest = testFactory.createAuthor(true);
        Book__c bookForTest = testFactory.createBook(publisherForTest.Id, authorForTest.Id, false);
        List<Book__c> bookListForTest = new List<Book__c>{ bookForTest };

        // create mock
        Mocker bookSelectorMocker = new Mocker(BookSelector.class)
            .setBehavior('getListByISBNs', new List<Book__c>{});
        ObjectFactory.mocks.put(
            BookSelector.class.getName(),
            (BookSelector) bookSelectorMocker.getMock()
        );

        // execute
        GetDuplicateBooksService service = new GetDuplicateBooksService();
        Map<String, List<Book__c>> duplicateLists = service.getDuplicates(bookListForTest);

        // assert
        bookSelectorMocker.assertMethodExecutionCount('getListByISBNs', 1);
    }
}