force-app/main/default/objects/Author__c/Author__c.object-meta.xml
<CustomObject>
    <label>Author</label>
    <nameField>
        <displayFormat>AP-{0000}</displayFormat>
        <label>Author Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Authors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Author_Publisher__c/Author_Publisher__c.object-meta.xml
<CustomObject>
    <label>Author_Publisher</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Author_Publisher Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Author_Publishers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Author_Publisher__c/fields/Author__c.field-meta.xml
<CustomField>
    <fullName>Author__c</fullName>
    <label>Author</label>
    <referenceTo>Author__c</referenceTo>
    <relationshipLabel>Author_Publishers</relationshipLabel>
    <relationshipName>Author_Publishers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Author_Publisher__c/fields/Publisher__c.field-meta.xml
<CustomField>
    <fullName>Publisher__c</fullName>
    <label>Publisher</label>
    <referenceTo>Publisher__c</referenceTo>
    <relationshipLabel>Author_Publishers</relationshipLabel>
    <relationshipName>Author_Publishers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Publisher__c/Publisher__c.object-meta.xml
<CustomObject>
    <label>Publisher</label>
    <nameField>
        <label>Publisher Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Publishers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/test/default/classes/unit/GetRelatedBooksOnAuthPubDelServiceTest.cls
/*
 * Class used for testng GetRelatedBooksOnAuthPubDelService
 */
@isTest
public with sharing class GetRelatedBooksOnAuthPubDelServiceTest {
    @isTest
    public static void getRelatedBooks_willUseService() {
        // create data
        TestFactory testFactory = new TestFactory();
        Publisher__c publisherForTest = testFactory.createPublisher(true);
        Author__c authorForTest = testFactory.createAuthor(true);
        Author_Publisher__c authorPublisherForTest = testFactory
            .createAuthorPublisher(authorForTest.Id, publisherForTest.Id, true);

        // create mocks
        Mocker authorPublisherSelectorMocker = new Mocker(AuthorPublisherSelector.class)
            .setBehavior('getRecordById', authorPublisherForTest);
        ObjectFactory.mocks.put(
            AuthorPublisherSelector.class.getName(),
            (AuthorPublisherSelector) authorPublisherSelectorMocker.getMock()
        );

        Mocker authorPublisherDeleteValidationServiceMocker = new Mocker(AuthorPublisherDeleteValidationService.class)
            .setBehavior('validateAuthorPublisher', null)
            .setBehavior('getResponse', null);
        ObjectFactory.mocks.put(
            AuthorPublisherDeleteValidationService.class.getName(),
            (AuthorPublisherDeleteValidationService) authorPublisherDeleteValidationServiceMocker.getMock()
        );

        // execute
        GetRelatedBooksOnAuthPubDelService service = new GetRelatedBooksOnAuthPubDelService();
        service.getRelatedBooks(authorPublisherForTest.Id, 5);

        // Assert
        authorPublisherSelectorMocker.assertMethodExecutionCount('getRecordById', 1);
        authorPublisherDeleteValidationServiceMocker.assertMethodExecutionCount('validateAuthorPublisher', 1);
        authorPublisherDeleteValidationServiceMocker.assertMethodExecutionCount('getResponse', 1);
    }
}