force-app/main/default/objects/Author__c/Author__c.object-meta.xml
<CustomObject>
    <label>Author</label>
    <nameField>
        <displayFormat>AP-{0000}</displayFormat>
        <label>Author Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Authors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Author_Publisher__c/Author_Publisher__c.object-meta.xml
<CustomObject>
    <label>Author_Publisher</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Author_Publisher Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Author_Publishers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Author_Publisher__c/fields/Author__c.field-meta.xml
<CustomField>
    <fullName>Author__c</fullName>
    <label>Author</label>
    <referenceTo>Author__c</referenceTo>
    <relationshipLabel>Author_Publishers</relationshipLabel>
    <relationshipName>Author_Publishers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Author_Publisher__c/fields/Publisher__c.field-meta.xml
<CustomField>
    <fullName>Publisher__c</fullName>
    <label>Publisher</label>
    <referenceTo>Publisher__c</referenceTo>
    <relationshipLabel>Author_Publishers</relationshipLabel>
    <relationshipName>Author_Publishers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Book__c/Book__c.object-meta.xml
<CustomObject>
    <label>Book</label>
    <nameField>
        <label>Book Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Books</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Book__c/fields/Author__c.field-meta.xml
<CustomField>
    <fullName>Author__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Author</label>
    <referenceTo>Author__c</referenceTo>
    <relationshipLabel>Books</relationshipLabel>
    <relationshipName>Books</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Book__c/fields/Publisher__c.field-meta.xml
<CustomField>
    <fullName>Publisher__c</fullName>
    <label>Publisher</label>
    <referenceTo>Publisher__c</referenceTo>
    <relationshipLabel>Books</relationshipLabel>
    <relationshipName>Books</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Publisher__c/Publisher__c.object-meta.xml
<CustomObject>
    <label>Publisher</label>
    <nameField>
        <label>Publisher Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Publishers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/test/default/classes/integration/BookTriggerTest.cls
/*
* This class performs tests for Book__c trigger 
*/
@isTest
public with sharing class BookTriggerTest {
    //reusable details for the data to be created in tests
    private static Map<String, String> publisherDetails = new Map<String, String>{
        'name'=>'publisher',
        'email'=>'publisher@gmail.com',
        'phone'=>'1241353'
    };
    private static Map<String, String> authorDetails = new Map<String, String>{
        'firstName'=>'Author',
        'lastName'=>'Author'
    };
    private static Map<String, String> bookDetails = new Map<String, String>{
        'name'=>'book',
        'description'=>'bookdesc',
        'ISBN'=>'214215425',
        'language'=>'english',
        'categories'=>'fantasy'
    };

    @isTest
    public static void onInsert_willAddError_whenAuthorPublisherNotAdded() {
        //Create data for mocks and test
        TestFactory testFactory = new TestFactory();
        Publisher__c publisherForTest = testFactory.createPublisher(publisherDetails, true, false);
        Author__c authorForTest = testFactory.createAuthor(authorDetails, true, false);
        Book__c bookForTest = testFactory.createBook(publisherForTest.Id, authorForTest.Id, bookDetails, false, false);

        Test.startTest();
        Database.SaveResult insertResult = Database.insert(bookForTest, false);
        Test.stopTest();

        System.assert(insertResult.isSuccess() == false,'Result for book insert should not be a success');
    }

    @isTest
    public static void onUpdate_willAddError_whenNewAuthorPublisherNotAdded() {
        //Create data for mocks and test
        TestFactory testFactory = new TestFactory();
        Publisher__c publisherForTest = testFactory.createPublisher(publisherDetails, true, false);
        Author__c oldAuthorForTest = testFactory.createAuthor(authorDetails, true, false);
        Author_Publisher__c authorPublisherForMock = testFactory
        .createAuthorPublisher(oldAuthorForTest.Id, publisherForTest.Id, true, false);
        Book__c bookForTest = testFactory.createBook(publisherForTest.Id, oldAuthorForTest.Id, bookDetails, true, false);
        //Create new data for update
        Author__c newAuthorForTest = testFactory.createAuthor(authorDetails, false, true);
        bookForTest.Author__c=newAuthorForTest.Id;

        Test.startTest();
        Database.SaveResult updateResult = Database.update(bookForTest, false);
        Test.stopTest();

        System.assert(updateResult.isSuccess() == false,'Result for book update should not be a success');
    }
}