force-app/main/default/objects/Book_Reservation__c/Book_Reservation__c.object-meta.xml
<CustomObject>
    <label>Book Reservation</label>
    <nameField>
        <displayFormat>RES-{0000}</displayFormat>
        <label>Book Reservation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Book Reservations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Book_Reservation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Bought</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Service/BookReservationCancelationService.cls
public with sharing class BookReservationCancelationService {
    public void cancelBookReservation (List<Book_Reservation__c> bookReservations) {
        // bookReservation.Status__c = bookReservation.Status__c == 'Active' ? 'Canceled' : bookReservation.Status__c;
        //TODO Find Bookstore Book 
        // bookstoreBook.Number_Of_Active_Reservations__c -= bookReservation.Quantity__c;

        // Database.update(bookReservation);
        // Database.update(bookstoreBook);
    }
}