force-app/main/default/objects/Bookstore__c/Bookstore__c.object-meta.xml
<CustomObject>
    <label>Bookstore</label>
    <nameField>
        <label>Bookstore Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookstores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Bookstore_Publisher__c/Bookstore_Publisher__c.object-meta.xml
<CustomObject>
    <label>Bookstore_Publisher</label>
    <nameField>
        <displayFormat>BP-{0000}</displayFormat>
        <label>Bookstore Publisher Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookstore Publishers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bookstore_Publisher__c/fields/Bookstore__c.field-meta.xml
<CustomField>
    <fullName>Bookstore__c</fullName>
    <label>Bookstore</label>
    <referenceTo>Bookstore__c</referenceTo>
    <relationshipName>Bookstore_Publishers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Bookstore_Publisher__c/fields/Publisher__c.field-meta.xml
<CustomField>
    <fullName>Publisher__c</fullName>
    <label>Publisher</label>
    <referenceTo>Publisher__c</referenceTo>
    <relationshipName>Bookstore_Publishers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Publisher__c/Publisher__c.object-meta.xml
<CustomObject>
    <label>Publisher</label>
    <nameField>
        <label>Publisher Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Publishers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/test/default/classes/unit/GetPageReferenceForBookstorePublsherTest.cls
/**
 * Class used for testing GetPageReferenceForBookstorePublsherService
 */
@isTest
public with sharing class GetPageReferenceForBookstorePublsherTest {
    @isTest
    public static void getPageReference_willReturnPageRef_ifIsCanceledIsTrue() {
        // create data
        TestFactory testFactory = new TestFactory();
        Publisher__c publisherForTest = testFactory.createPublisher(false, true);
        Bookstore__c bookstoreForTest = testFactory.createBookstore(false, true);
        Bookstore_Publisher__c bookstorePublisherForTest = testFactory
            .createBookstorePublisher(publisherForTest.Id, bookstoreForTest.Id, false, true);
        
        // execute
        GetPageReferenceForBookstorePublisher service = new GetPageReferenceForBookstorePublisher();
        service.getPageReference(true, false, false, bookstorePublisherForTest);

        // Assert
        Assert.isTrue(service.getResponse() != null);
    }

    @isTest
    public static void getPageReference_willReturnPageRef_ifDeleteStatusIsFalse() {
        // create data
        TestFactory testFactory = new TestFactory();
        Publisher__c publisherForTest = testFactory.createPublisher(false, true);
        Bookstore__c bookstoreForTest = testFactory.createBookstore(false, true);
        Bookstore_Publisher__c bookstorePublisherForTest = testFactory
            .createBookstorePublisher(publisherForTest.Id, bookstoreForTest.Id, false, true);
        
        // execute
        GetPageReferenceForBookstorePublisher service = new GetPageReferenceForBookstorePublisher();
        service.getPageReference(false, false, false, bookstorePublisherForTest);

        // Assert
        Assert.isTrue(service.getResponse() != null);
    }

    @isTest
    public static void getPageReference_willReturnPageRef_ifviewAllIsClicked() {
        // create data
        TestFactory testFactory = new TestFactory();
        Publisher__c publisherForTest = testFactory.createPublisher(false, true);
        Bookstore__c bookstoreForTest = testFactory.createBookstore(false, true);
        Bookstore_Publisher__c bookstorePublisherForTest = testFactory
            .createBookstorePublisher(publisherForTest.Id, bookstoreForTest.Id, false, true);
        
        // execute
        GetPageReferenceForBookstorePublisher service = new GetPageReferenceForBookstorePublisher();
        service.getPageReference(false, true, true, bookstorePublisherForTest);

        // Assert
        Assert.isTrue(service.getResponse() != null);
    }

    @isTest
    public static void getPageReference_willReturnNull_ifNoButtonsWereClickedAndDeleteStatusIsTrue() {
        // create data
        TestFactory testFactory = new TestFactory();
        Publisher__c publisherForTest = testFactory.createPublisher(false, true);
        Bookstore__c bookstoreForTest = testFactory.createBookstore(false, true);
        Bookstore_Publisher__c bookstorePublisherForTest = testFactory
            .createBookstorePublisher(publisherForTest.Id, bookstoreForTest.Id, false, true);
        
        // execute
        GetPageReferenceForBookstorePublisher service = new GetPageReferenceForBookstorePublisher();
        service.getPageReference(false, false, true, bookstorePublisherForTest);

        // Assert
        Assert.isTrue(service.getResponse() == null);
    }
}