force-app/main/default/objects/Bookstore__c/Bookstore__c.object-meta.xml
<CustomObject>
    <label>Bookstore</label>
    <nameField>
        <label>Bookstore Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookstores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Bookstore_Publisher__c/Bookstore_Publisher__c.object-meta.xml
<CustomObject>
    <label>Bookstore_Publisher</label>
    <nameField>
        <displayFormat>BP-{0000}</displayFormat>
        <label>Bookstore Publisher Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookstore Publishers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bookstore_Publisher__c/fields/Bookstore__c.field-meta.xml
<CustomField>
    <fullName>Bookstore__c</fullName>
    <label>Bookstore</label>
    <referenceTo>Bookstore__c</referenceTo>
    <relationshipName>Bookstore_Publishers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Bookstore_Publisher__c/fields/Publisher__c.field-meta.xml
<CustomField>
    <fullName>Publisher__c</fullName>
    <label>Publisher</label>
    <referenceTo>Publisher__c</referenceTo>
    <relationshipName>Bookstore_Publishers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Publisher__c/Publisher__c.object-meta.xml
<CustomObject>
    <label>Publisher</label>
    <nameField>
        <label>Publisher Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Publishers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/test/default/classes/TestFactory/BookstorePublisherTestFactory.cls
/*
* Class used for creating Bookstore_Publisher__c objects only for tests
*/
@isTest
public with sharing class BookstorePublisherTestFactory {
    /*
    * @param numOfbkStorePublishers - number of objects to be created
    * @param publisherId - Id of a Publisher__c which is a parent in master-detail relationship
    * @param bookstoreId - Id of a Bookstore__c which is a parent in master-detail relationship
    */
    public List<Bookstore_Publisher__c> createBookstorePublishers(Integer numOfbkStorePublishers,
    Id publisherId, Id bookstoreId) {
        List<Bookstore_Publisher__c> BookstorePublishersForTest = new List<Bookstore_Publisher__c>();
        for(Integer i = 0; i<numOfbkStorePublishers; i++) {
            Bookstore_Publisher__c currentBkstorePublisher = new Bookstore_Publisher__c();
            currentBkstorePublisher.Publisher__c = publisherId;
            currentBkstorePublisher.Bookstore__c = bookstoreId;
            BookstorePublishersForTest.add(currentBkstorePublisher);
        }
        return BookstorePublishersForTest;
    }
}