force-app/main/default/objects/Bookstore__c/Bookstore__c.object-meta.xml
<CustomObject>
    <label>Bookstore</label>
    <nameField>
        <label>Bookstore Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookstores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Bookstore_Publisher__c/Bookstore_Publisher__c.object-meta.xml
<CustomObject>
    <label>Bookstore_Publisher</label>
    <nameField>
        <displayFormat>BP-{0000}</displayFormat>
        <label>Bookstore Publisher Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookstore Publishers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bookstore_Publisher__c/fields/Bookstore__c.field-meta.xml
<CustomField>
    <fullName>Bookstore__c</fullName>
    <label>Bookstore</label>
    <referenceTo>Bookstore__c</referenceTo>
    <relationshipName>Bookstore_Publishers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Bookstore_Publisher__c/fields/Publisher__c.field-meta.xml
<CustomField>
    <fullName>Publisher__c</fullName>
    <label>Publisher</label>
    <referenceTo>Publisher__c</referenceTo>
    <relationshipName>Bookstore_Publishers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Publisher__c/Publisher__c.object-meta.xml
<CustomObject>
    <label>Publisher</label>
    <nameField>
        <label>Publisher Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Publishers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/test/default/classes/unit/BookstorePublisherSelectorTest.cls
/*
* This class performs tests for Bookstore_Publisher__c selectors
*/
@isTest
public with sharing class BookstorePublisherSelectorTest {
    @isTest
    public static void getBookstorePublisherByPublisherIdAndBookstoreId_willReturnFiveBookstorePublishers_ifFiveBookstorePublishersInserted() {
        List<Bookstore__c> bookstoreForInsert = new TestFactory().createBookstores(1);
        insert bookstoreForInsert;
        List<Publisher__c> publisherForInsert = new TestFactory().createPublishers(1);
        insert publisherForInsert;
        List<Bookstore_Publisher__c> bkStorePublisherForInsert = new TestFactory()
        .createBookstorePublishers(5, publisherForInsert[0].Id,  bookstoreForInsert[0].Id);
        insert bkStorePublisherForInsert;

        Test.startTest();
        List<Bookstore_Publisher__c> bkStorePublishersForTest = new BookstorePublisherSelector()
        .getAllBookstorePublishers();
        Test.stopTest();
        
        System.assertEquals(bkStorePublishersForTest[0].Id, bkStorePublisherForInsert[0].Id);
        System.assertEquals(bkStorEPublishersForTest.size(), bkStorePublisherForInsert.size());
    }
}