force-app/main/default/objects/Bookstore__c/Bookstore__c.object-meta.xml
<CustomObject>
    <label>Bookstore</label>
    <nameField>
        <label>Bookstore Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookstores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Bookstore__c/fields/Store_Identification_Code__c.field-meta.xml
<CustomField>
    <fullName>Store_Identification_Code__c</fullName>
    <label>Store Identification Code</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/test/default/classes/TestFactory/BookstoreTestFactory.cls
/*
* Class used for creating Bookstore__c objects only for tests
*/
@isTest
public with sharing class BookstoreTestFactory {
    /*
    * @param numOfBookstores - number of Bookstore__c objects to be inserted
    */
    public List<Bookstore__c> createBookstores(Integer numOfBookstores) {
        List<Bookstore__c> bookstoresForTest = new List<Bookstore__c>();
        for(Integer i = 0;i<numOfBookstores; i++) {
            Bookstore__c currentBookstore = new Bookstore__c();
            currentBookstore.Name = 'Bookstore' + i;
            currentBookstore.Email__c = 'bookstore' + i + '@gmail.com';
            currentBookstore.Store_Identification_Code__c = '12i245' + i;
            bookstoresForTest.add(currentBookstore);
        }
        return bookstoresForTest;
    }
}