force-app/main/default/objects/Bookstore__c/Bookstore__c.object-meta.xml
<CustomObject>
    <label>Bookstore</label>
    <nameField>
        <label>Bookstore Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookstores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Bookstore_Book__c/Bookstore_Book__c.object-meta.xml
<CustomObject>
    <label>Bookstore_Book</label>
    <nameField>
        <label>Bookstore_Book Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookstore_Books</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bookstore_Book__c/fields/Bookstore__c.field-meta.xml
<CustomField>
    <fullName>Bookstore__c</fullName>
    <label>Bookstore</label>
    <referenceTo>Bookstore__c</referenceTo>
    <relationshipLabel>Bookstore Books</relationshipLabel>
    <relationshipName>Bookstore_Books</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Bookstore_Publisher__c/Bookstore_Publisher__c.object-meta.xml
<CustomObject>
    <label>Bookstore_Publisher</label>
    <nameField>
        <displayFormat>BP-{0000}</displayFormat>
        <label>Bookstore Publisher Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookstore Publishers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bookstore_Publisher__c/fields/Bookstore__c.field-meta.xml
<CustomField>
    <fullName>Bookstore__c</fullName>
    <label>Bookstore</label>
    <referenceTo>Bookstore__c</referenceTo>
    <relationshipName>Bookstore_Publishers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Bookstore_Publisher__c/fields/Publisher__c.field-meta.xml
<CustomField>
    <fullName>Publisher__c</fullName>
    <label>Publisher</label>
    <referenceTo>Publisher__c</referenceTo>
    <relationshipName>Bookstore_Publishers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Publisher__c/Publisher__c.object-meta.xml
<CustomObject>
    <label>Publisher</label>
    <nameField>
        <label>Publisher Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Publishers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/test/default/classes/unit/GetBokstoreBooksOnPblsherDeleteTest.cls
/**
 * Class used for testing GetBookstoreBooksOnPublihserDeleteService
 */
@isTest
public with sharing class GetBokstoreBooksOnPblsherDeleteTest {
    @isTest
    public static void getBookstoreBooks_willNotAddError_ifBookstoreBookWithSamePublisherDoesentExists() {
        // create data
        TestFactory testFactory = new TestFactory();
        Publisher__c publisherForTest = testFactory.createPublisher(false, true);
        Bookstore__c bookstoreForTest = testFactory.createBookstore(false, true);
        Bookstore_Publisher__c bookstorePublisherForTest = testFactory
            .createBookstorePublisher(publisherForTest.Id, bookstoreForTest.Id, false, true);

        // create mock
        Mocker BookstorePublisherSelectorMocker = new Mocker(BookstorePublisherSelector.class)
            .setBehavior('getRecordById', bookstorePublisherForTest);
        ObjectFactory.mocks.put(
            BookstorePublisherSelector.class.getName(),
            (BookstorePublisherSelector) BookstorePublisherSelectorMocker.getMock()
        );

        Mocker BookstoreBookSelectorMocker = new Mocker(BookstoreBookSelector.class)
            .setBehavior('getListByBookstoreId', new List<Bookstore_Book__c>{});
        ObjectFactory.mocks.put(
            BookstoreBookSelector.class.getName(),
            (BookstoreBookSelector) BookstoreBookSelectorMocker.getMock()
        );

        // execute
        GetBokstoreBooksOnPublsherDeleteService service = new GetBokstoreBooksOnPublsherDeleteService();
        service.getBookstoreBooks(bookstorePublisherForTest.Id, 5);

        // Assert
        Assert.isTrue(bookstorePublisherForTest.getErrors().size() == 0);
    }

    @isTest
    public static void getBookstoreBooks_willUseSelectors() {
        // create data
        TestFactory testFactory = new TestFactory();
        Publisher__c publisherForTest = testFactory.createPublisher(false, true);
        Bookstore__c bookstoreForTest = testFactory.createBookstore(false, true);
        Bookstore_Publisher__c bookstorePublisherForTest = testFactory
            .createBookstorePublisher(publisherForTest.Id, bookstoreForTest.Id, false, true);

        // create mock
        Mocker BookstorePublisherSelectorMocker = new Mocker(BookstorePublisherSelector.class)
            .setBehavior('getRecordById', bookstorePublisherForTest);
        ObjectFactory.mocks.put(
            BookstorePublisherSelector.class.getName(),
            (BookstorePublisherSelector) BookstorePublisherSelectorMocker.getMock()
        );

        Mocker BookstoreBookSelectorMocker = new Mocker(BookstoreBookSelector.class)
            .setBehavior('getListByBookstoreId', new List<Bookstore_Book__c>{});
        ObjectFactory.mocks.put(
            BookstoreBookSelector.class.getName(),
            (BookstoreBookSelector) BookstoreBookSelectorMocker.getMock()
        );

        // execute
        GetBokstoreBooksOnPublsherDeleteService service = new GetBokstoreBooksOnPublsherDeleteService();
        service.getBookstoreBooks(bookstorePublisherForTest.Id, 5);

        // Assert
        BookstorePublisherSelectorMocker.assertMethodExecutionCount('getRecordById', 1);
        BookstoreBookSelectorMocker.assertMethodExecutionCount('getListByBookstoreId', 1);
    }
}