force-app/main/default/objects/Bookstore__c/Bookstore__c.object-meta.xml
<CustomObject>
    <label>Bookstore</label>
    <nameField>
        <label>Bookstore Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookstores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Bookstore_Publisher__c/Bookstore_Publisher__c.object-meta.xml
<CustomObject>
    <label>Bookstore_Publisher</label>
    <nameField>
        <displayFormat>BP-{0000}</displayFormat>
        <label>Bookstore Publisher Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookstore Publishers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bookstore_Publisher__c/fields/Bookstore__c.field-meta.xml
<CustomField>
    <fullName>Bookstore__c</fullName>
    <label>Bookstore</label>
    <referenceTo>Bookstore__c</referenceTo>
    <relationshipName>Bookstore_Publishers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/Service/BookstorePublsherDeleteValidationService.cls
/*
 * Class responsible for stopping delete of Bookstore_Publisher__c record if Bookstore__Book__c record exist assigned to the same Bookstore__c record
 */
public with sharing class BookstorePublsherDeleteValidationService {
    /*
     * @param deletedRecords - Bookstore_Publisher__c records being deleted
     */
    public void validateBookstorePublisher(List<Bookstore_Publisher__c> deletedRecords) {
        // Set that holds Ids of deleted Bookstore_Publisher__c records
        Set<Id> bookstorePublisherIds = new Set<Id>();
        // Loop through deleted records and add their Ids to the set
        for (Bookstore_Publisher__c bookstorePublisher : deletedRecords) {
            bookstorePublisherIds.add(bookstorePublisher.Id);
        }
        
    }
}