force-app/main/default/objects/Bookstore__c/Bookstore__c.object-meta.xml
<CustomObject>
    <label>Bookstore</label>
    <nameField>
        <label>Bookstore Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookstores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Bookstore_Book__c/Bookstore_Book__c.object-meta.xml
<CustomObject>
    <label>Bookstore_Book</label>
    <nameField>
        <label>Bookstore_Book Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookstore_Books</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bookstore_Book__c/fields/Bookstore__c.field-meta.xml
<CustomField>
    <fullName>Bookstore__c</fullName>
    <label>Bookstore</label>
    <referenceTo>Bookstore__c</referenceTo>
    <relationshipLabel>Bookstore Books</relationshipLabel>
    <relationshipName>Bookstore_Books</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Bookstore_Publisher__c/Bookstore_Publisher__c.object-meta.xml
<CustomObject>
    <label>Bookstore_Publisher</label>
    <nameField>
        <displayFormat>BP-{0000}</displayFormat>
        <label>Bookstore Publisher Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookstore Publishers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bookstore_Publisher__c/fields/Bookstore__c.field-meta.xml
<CustomField>
    <fullName>Bookstore__c</fullName>
    <label>Bookstore</label>
    <referenceTo>Bookstore__c</referenceTo>
    <relationshipName>Bookstore_Publishers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Bookstore_Publisher__c/fields/Publisher__c.field-meta.xml
<CustomField>
    <fullName>Publisher__c</fullName>
    <label>Publisher</label>
    <referenceTo>Publisher__c</referenceTo>
    <relationshipName>Bookstore_Publishers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Publisher__c/Publisher__c.object-meta.xml
<CustomObject>
    <label>Publisher</label>
    <nameField>
        <label>Publisher Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Publishers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/test/default/classes/unit/BookstorePublisherDeleteValidationTest.cls
/**
 * Class performs unit tests for BookstorePublisherDeleteValidatonService
 */
@isTest
public with sharing class BookstorePublisherDeleteValidationTest {
    @isTest
    public static void validatePublisher_willNotAddError_ifBookstoreBookWithSamePublisherDoesentExist() {
        // create data
        TestFactory testFactory = new TestFactory();
        Publisher__c publisherForTest = testFactory.createPublisher(true);
        Bookstore__c bookstoreForTest = testFactory.createBookstore(true);
        Bookstore_Publisher__c bookstorePublisherForTest = testFactory
            .createBookstorePublisher(publisherForTest.Id, bookstoreForTest.Id, true);

        // create mock
        Mocker BookstoreBookSelectorMocker = new Mocker(BookstoreBookSelector.class)
            .setBehavior('getListByBookstoreIds', new List<Bookstore_Book__c>{});
        ObjectFactory.mocks.put(
            BookstoreBookSelector.class.getName(),
            (BookstoreBookSelector) BookstoreBookSelectorMocker.getMock()
        );

        // execute
        BookstorePublsherDeleteValidationService service = new BookstorePublsherDeleteValidationService();
        service.validateBookstorePublisher(new List<Bookstore_Publisher__c>{ bookstorePublisherForTest }, 2000);

        // Assert
        Assert.isTrue(bookstorePublisherForTest.getErrors().size() == 0);
    }
    
    @isTest
    public static void validatePublisher_willUseSelector() {
        // create data
        TestFactory testFactory = new TestFactory();
        Publisher__c publisherForTest = testFactory.createPublisher(true);
        Bookstore__c bookstoreForTest = testFactory.createBookstore(true);
        Bookstore_Publisher__c bookstorePublisherForTest = testFactory
            .createBookstorePublisher(publisherForTest.Id, bookstoreForTest.Id, true);

        // create mock
        Mocker BookstoreBookSelectorMocker = new Mocker(BookstoreBookSelector.class)
            .setBehavior('getListByBookstoreIds', new List<Bookstore_Book__c>{});
        ObjectFactory.mocks.put(
            BookstoreBookSelector.class.getName(),
            (BookstoreBookSelector) BookstoreBookSelectorMocker.getMock()
        );

        // execute
        BookstorePublsherDeleteValidationService service = new BookstorePublsherDeleteValidationService();
        service.validateBookstorePublisher(new List<Bookstore_Publisher__c>{ bookstorePublisherForTest }, 2000);

        // Assert
        BookstoreBookSelectorMocker.assertMethodExecutionCount('getListByBookstoreIds', 1);
    }
}