force-app/main/default/objects/Bookstore__c/Bookstore__c.object-meta.xml
<CustomObject>
    <label>Bookstore</label>
    <nameField>
        <label>Bookstore Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookstores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Bookstore__c/fields/Manager__c.field-meta.xml
<CustomField>
    <fullName>Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Bookstores</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Service/BookstoreValidationService.cls
/**
 * Class that contains a method to validate if a User is already a Bookstore manager
 * 
 * @see BookstoreTriggerHandler.cls
 */
public with sharing class BookstoreValidationService implements CustomObject {

    /**
     * Method that checks if some Bookstore already contains certain User's Id
     * 
     * @param newBookstores list of new Bookstore records
     */
    public void validateBookstoreManagerMatch(List<Bookstore__c> newBookstores) {
        //Get all Bookstore__c sObjects
        BookstoreSelector bookstoreSelector = (BookstoreSelector) new ObjectFactory().createObject(BookstoreSelector.class);
        List<Bookstore__c> bookstores = bookstoreSelector.getList();

        /**
         * Iterate through new Bookstores.
         * For each new Bookstore, iterate through existing Bookstores returned by
         * selector.
         * Check if existing Bookstore is related to User we want to relate a new 
         * Booktore to
         */
        for (Bookstore__c newBookstore:newBookstores) {
            for (Bookstore__c bookstore:bookstores) {
                if (newBookstore.Manager__c != null && bookstore.Manager__c != null && newBookstore.Manager__c == bookstore.Manager__c) {
                    newBookstore.addError('User is already a Bookstore Manager!');
                    break;
                }
            }
        }
    }
}