force-app/main/default/objects/Bookstore__c/Bookstore__c.object-meta.xml
<CustomObject>
    <label>Bookstore</label>
    <nameField>
        <label>Bookstore Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookstores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Bookstore__c/fields/Manager__c.field-meta.xml
<CustomField>
    <fullName>Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Bookstores</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/test/default/classes/integration/BookstoreTriggerTest.cls
/**
 * This class performs tests for Bookstore__c object trigger
 * 
 * @see BookstoreTrigger.trigger
 */
@isTest
public with sharing class BookstoreTriggerTest {
    @isTest
    public static void onInsert_WillAddError_IfUserIsManagerOfSomeBookstore() {
        // create data
        TestFactory testFactory = new TestFactory();
        User userForTest = testFactory.createUser(true, false);
        Bookstore__c bookstore1 = testFactory.createBookstore(true, false);
        //make user manager of the bookstore
        bookstore1.Manager__c = userForTest.Id;
        update bookstore1;
        Bookstore__c bookstore2 = testFactory.createBookstore(false, true);
        //make user manager of the bookstore
        bookstore2.Manager__c = userForTest.Id;

        Test.startTest();
        Database.SaveResult insertResult = Database.insert(bookstore2, false);
        Test.stopTest();

        Assert.isTrue(insertResult.getErrors().size() == 1);
    }

    @isTest
    public static void onUpdate_WillAddError_IfUserIsManagerOfSomeBookstore() {
        // create data
        TestFactory testFactory = new TestFactory();
        User userForTest = testFactory.createUser(true, false);
        Bookstore__c bookstore1 = testFactory.createBookstore(true, false);
        //make user manager of the bookstore
        bookstore1.Manager__c = userForTest.Id;
        update bookstore1;
        Bookstore__c bookstore2 = testFactory.createBookstore(true, false);
        //make user manager of the bookstore
        bookstore2.Manager__c = userForTest.Id;

        Test.startTest();
        Database.SaveResult updateResult = Database.update(bookstore2, false);
        Test.stopTest();

        Assert.isTrue(updateResult.getErrors().size() == 1);
    }
}