force-app/main/default/objects/Bookstore__c/Bookstore__c.object-meta.xml
<CustomObject>
    <label>Bookstore</label>
    <nameField>
        <label>Bookstore Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookstores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Bookstore_Publisher__c/Bookstore_Publisher__c.object-meta.xml
<CustomObject>
    <label>Bookstore_Publisher</label>
    <nameField>
        <displayFormat>BP-{0000}</displayFormat>
        <label>Bookstore Publisher Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookstore Publishers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bookstore_Publisher__c/fields/Bookstore__c.field-meta.xml
<CustomField>
    <fullName>Bookstore__c</fullName>
    <label>Bookstore</label>
    <referenceTo>Bookstore__c</referenceTo>
    <relationshipName>Bookstore_Publishers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Bookstore_Publisher__c/fields/Publisher__c.field-meta.xml
<CustomField>
    <fullName>Publisher__c</fullName>
    <label>Publisher</label>
    <referenceTo>Publisher__c</referenceTo>
    <relationshipName>Bookstore_Publishers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Publisher__c/Publisher__c.object-meta.xml
<CustomObject>
    <label>Publisher</label>
    <nameField>
        <label>Publisher Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Publishers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/test/default/classes/unit/GetPublishersNotWithBookstoreServiceTest.cls
/*
* Class used to perform unit tests for this service
* Class will perform 3 tests: 1 positive, 1 negative and one for asserting method execution count for mockers
*/
@isTest
public with sharing class GetPublishersNotWithBookstoreServiceTest {
    @isTest
    public static void getPublishers_willReturnPublisher_ifBookstorePublisherNotCreated() {
        //Create data for mocks and test
        TestFactory testFactory = new TestFactory();
        Map<String, String> publisherDetails = new Map<String, String>();
        publisherDetails.put('name', 'publisher');
        publisherDetails.put('email', 'publisher@gmail.com');
        publisherDetails.put('phone', '1241353');
        Publisher__c publisherForTest = testFactory.createPublisher(publisherDetails, false, true);

        Map<String, String> bookstoreDetails = new Map<String, String>();
        bookstoreDetails.put('name', 'bookstore');
        bookstoreDetails.put('email', 'bookstore@gmail.com');
        bookstoreDetails.put('storeId', '1241353');
        Bookstore__c bookstoreForTest = testFactory.createBookstore(bookstoreDetails, false, true);

        Bookstore_Publisher__c bookstorePublisherForTest = new Bookstore_Publisher__c();

        Mocker BookstorePublisherSelectorMock = new Mocker(BookstorePublisherSelector.class)
        .setBehavior('getListByBookstoreId', new List<Bookstore_Publisher__c>{bookstorePublisherForTest});

        ObjectFactory.mocks.put(
            BookstorePublisherSelector.class.getName(),
            (BookstorePublisherSelector) BookstorePublisherSelectorMock.getMock()
        );

        Mocker PublisherSelectorMock = new Mocker(PublisherSelector.class)
        .setBehavior('getPublishersNotInSet', new List<Publisher__c>{publisherForTest});
        
        ObjectFactory.mocks.put(
            PublisherSelector.class.getName(),
            (PublisherSelector) PublisherSelectorMock.getMock()
        );

        GetPublishersNotWithBookstoreService service = new GetPublishersNotWithBookstoreService();
        service.getPublishers(bookstoreForTest.Id);
        List<Publisher__c> publishersNotWorkingWithBookstore = service.getResponse();

        System.assertEquals(1, publishersNotWorkingWithBookstore.size());
    }

    @isTest
    public static void getPublishers_willNotReturnPublisher_ifBookstorePublisherWasCreated() {
        //Create data for mocks and test
        TestFactory testFactory = new TestFactory();
        Map<String, String> publisherDetails = new Map<String, String>();
        publisherDetails.put('name', 'publisher');
        publisherDetails.put('email', 'publisher@gmail.com');
        publisherDetails.put('phone', '1241353');
        Publisher__c publisherForTest = testFactory.createPublisher(publisherDetails, false, true);

        Map<String, String> bookstoreDetails = new Map<String, String>();
        bookstoreDetails.put('name', 'bookstore');
        bookstoreDetails.put('email', 'bookstore@gmail.com');
        bookstoreDetails.put('storeId', '1241353');
        Bookstore__c bookstoreForTest = testFactory.createBookstore(bookstoreDetails, false, true);

        Bookstore_Publisher__c bookstorePublisherForTest = testFactory.createBookstorePublisher(publisherForTest.Id, bookstoreForTest.Id, false, true);

        Mocker BookstorePublisherSelectorMock = new Mocker(BookstorePublisherSelector.class)
        .setBehavior('getListByBookstoreId', new List<Bookstore_Publisher__c>{bookstorePublisherForTest});

        ObjectFactory.mocks.put(
            BookstorePublisherSelector.class.getName(),
            (BookstorePublisherSelector) BookstorePublisherSelectorMock.getMock()
        );

        Mocker PublisherSelectorMock = new Mocker(PublisherSelector.class)
        .setBehavior('getPublishersNotInSet', new List<Publisher__c>{});
        
        ObjectFactory.mocks.put(
            PublisherSelector.class.getName(),
            (PublisherSelector) PublisherSelectorMock.getMock()
        );

        GetPublishersNotWithBookstoreService service = new GetPublishersNotWithBookstoreService();
        service.getPublishers(bookstoreForTest.Id);
        List<Publisher__c> publishersNotWorkingWithBookstore = service.getResponse();

        System.assertEquals(0, publishersNotWorkingWithBookstore.size());
    }

    @isTest
    public static void getPublishers_willUseCorrectSelectors() {
        //Create data for mocks and test
        TestFactory testFactory = new TestFactory();
        Map<String, String> publisherDetails = new Map<String, String>();
        publisherDetails.put('name', 'publisher');
        publisherDetails.put('email', 'publisher@gmail.com');
        publisherDetails.put('phone', '1241353');
        Publisher__c publisherForTest = testFactory.createPublisher(publisherDetails, false, true);

        Map<String, String> bookstoreDetails = new Map<String, String>();
        bookstoreDetails.put('name', 'bookstore');
        bookstoreDetails.put('email', 'bookstore@gmail.com');
        bookstoreDetails.put('storeId', '1241353');
        Bookstore__c bookstoreForTest = testFactory.createBookstore(bookstoreDetails, false, true);

        Bookstore_Publisher__c bookstorePublisherForTest = testFactory.createBookstorePublisher(publisherForTest.Id, bookstoreForTest.Id, false, true);

        Mocker BookstorePublisherSelectorMock = new Mocker(BookstorePublisherSelector.class)
        .setBehavior('getListByBookstoreId', new List<Bookstore_Publisher__c>{bookstorePublisherForTest});

        ObjectFactory.mocks.put(
            BookstorePublisherSelector.class.getName(),
            (BookstorePublisherSelector) BookstorePublisherSelectorMock.getMock()
        );

        Mocker PublisherSelectorMock = new Mocker(PublisherSelector.class)
        .setBehavior('getPublishersNotInSet', new List<Publisher__c>{});
        
        ObjectFactory.mocks.put(
            PublisherSelector.class.getName(),
            (PublisherSelector) PublisherSelectorMock.getMock()
        );

        GetPublishersNotWithBookstoreService service = new GetPublishersNotWithBookstoreService();
        service.getPublishers(bookstoreForTest.Id);

        PublisherSelectorMock.assertMethodExecutionCount('getPublishersNotInSet', 1);
        BookstorePublisherSelectorMock.assertMethodExecutionCount('getListByBookstoreId', 1);
    }
}