force-app/main/default/objects/Bookstore__c/Bookstore__c.object-meta.xml
<CustomObject>
    <label>Bookstore</label>
    <nameField>
        <label>Bookstore Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookstores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Bookstore_Publisher__c/Bookstore_Publisher__c.object-meta.xml
<CustomObject>
    <label>Bookstore_Publisher</label>
    <nameField>
        <displayFormat>BP-{0000}</displayFormat>
        <label>Bookstore Publisher Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookstore Publishers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bookstore_Publisher__c/fields/Bookstore__c.field-meta.xml
<CustomField>
    <fullName>Bookstore__c</fullName>
    <label>Bookstore</label>
    <referenceTo>Bookstore__c</referenceTo>
    <relationshipName>Bookstore_Publishers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/Service/GetPageReferenceForBookstorePublisher.cls
/*
 * This class is used for returning Pagereference for BookstorePublisherController
 */
public with sharing class GetPageReferenceForBookstorePublisher implements CustomObject{
    private Pagereference response;

    //Getter
    public Pagereference getResponse() {
        return this.response;
    }

    //Setter
    public void setResponse(Pagereference pageReference) {
        this.response = pageReference;
    }
    
    /**
     * @param isCanceled - Boolean representing if the cancel button was clicke
     * @param deleteStatus - Boolean representing if the deletion result was successfull or not
     * @param bookstorePublisherId - Id of Bookstore_Publisher__c record being deleted
     */
    public void getPageReference(Boolean isCanceled, Boolean isViewAllClicked, Boolean deleteStatus, Bookstore_Publisher__c bookstorePublisherForDelete) { 
        if (isCanceled || !deleteStatus) {
            // Set the response that redirects to the bookstore detil view page of the record being deleted
            this.setResponse(new PageReference('/' + bookstorePublisherForDelete.Bookstore__c));
        } else if (isViewAllClicked) {
            this.setResponse(new PageReference('/lightning/n/Books_preventing_publisher_removal?c__recordId=' + bookstorePublisherForDelete.Id));       
        } else {
            this.setResponse(null);
        }
    }
}