force-app/main/default/objects/Publisher__c/Publisher__c.object-meta.xml
<CustomObject>
    <label>Publisher</label>
    <nameField>
        <label>Publisher Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Publishers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Publisher__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <description>Publishers phone</description>
    <label>Phone</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

force-app/main/default/classes/Repository/Selector/PublisherSelector.cls
/*
 * Class used for selectors regarding Publisher__c object
 */
public with sharing class PublisherSelector implements CustomObject{
    /*
     * @param publisherIds - set of publisher Ids which should no tbe retrieved
     */
    public List<Publisher__c> getListNotInIds(Set<Id> publisherIds, Integer recordLimit) {
        return [
            SELECT
                Id,
                Name,
                Phone__c
            FROM Publisher__c
            WHERE Id NOT IN : publisherIds
            LIMIT :recordLimit
        ];
    }

}