force-app/main/default/objects/Book__c/Book__c.object-meta.xml
<CustomObject>
    <label>Book</label>
    <nameField>
        <label>Book Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Books</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Book_Purchase__c/Book_Purchase__c.object-meta.xml
<CustomObject>
    <label>Book Purchase</label>
    <nameField>
        <displayFormat>BP-{0000}</displayFormat>
        <label>Book Purchase Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Book Purchases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Book_Purchase__c/fields/Book__c.field-meta.xml
<CustomField>
    <fullName>Book__c</fullName>
    <label>Book</label>
    <referenceTo>Book__c</referenceTo>
    <relationshipLabel>Book Purchases</relationshipLabel>
    <relationshipName>Book_Purchases</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/Service/InsertBookPurchaseRecordService.cls
/*
 * This class is used for inserting Book_Purchase__c record after purchasing digital book
 */
public with sharing class InsertBookPurchaseRecordService implements CustomObject{
    private Database.SaveResult response;

    //Getter
    public Database.SaveResult getResponse() {
        return this.response;
    }

    //Setter
    public void setResponse(Database.SaveResult purchaseInsert) {
        this.response = purchaseInsert;
    }
    
    /*
     * @param bookId - Id of the book purchased
     * The id of the user will be documented as createdById since only the users that are buying the book can insert this object
     */
    public void insertPurchase(Id bookId) { 
        Book_Purchase__c purchase = new Book_Purchase__c();
        purchase.Book__c = bookId;
        Database.SaveResult insertResult = Database.insert(purchase);
        this.setResponse(insertResult);
    }
}