force-app/main/default/objects/Book__c/Book__c.object-meta.xml
<CustomObject>
    <label>Book</label>
    <nameField>
        <label>Book Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Books</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Book__c/fields/Categories__c.field-meta.xml
<CustomField>
    <fullName>Categories__c</fullName>
    <description>Genres the book belongs to</description>
    <inlineHelpText>Genres the book belongs to</inlineHelpText>
    <label>Categories</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Book__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Book description</description>
    <inlineHelpText>Book description</inlineHelpText>
    <label>Description</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Book__c/fields/ISBN__c.field-meta.xml
<CustomField>
    <fullName>ISBN__c</fullName>
    <description>Unique book identifier</description>
    <inlineHelpText>Unique book identifier</inlineHelpText>
    <label>ISBN</label>
    <length>13</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Book__c/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <description>Language of the Book</description>
    <inlineHelpText>Language of the Book</inlineHelpText>
    <label>Language</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Book__c/fields/Publish_Date__c.field-meta.xml
<CustomField>
    <fullName>Publish_Date__c</fullName>
    <description>Book publish date</description>
    <inlineHelpText>Book publish date</inlineHelpText>
    <label>Publish Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Book__c/fields/Publisher__c.field-meta.xml
<CustomField>
    <fullName>Publisher__c</fullName>
    <label>Publisher</label>
    <referenceTo>Publisher__c</referenceTo>
    <relationshipLabel>Books</relationshipLabel>
    <relationshipName>Books</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Publisher__c/Publisher__c.object-meta.xml
<CustomObject>
    <label>Publisher</label>
    <nameField>
        <label>Publisher Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Publishers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/test/default/classes/TestFactory/BookTestFactory.cls
/*
* Class used for creating Book__c objects only for tests
*/
@isTest
public with sharing class BookTestFactory {
    /*
    * @param numOfBooks - number of books to be created
    * @param publisherId - Id of a Publisher__c object which is a parent in master-detail relationship to Book__c
    */
    public List<Book__c> createBooks(Integer numOfBooks, Id publisherId) {
        List<Book__c> booksForTest = new List<Book__c>();
        for(Integer i = 0; i<numOfBooks; i++) {
            Book__c currentBook = new Book__c();
            currentBook.Name = 'Book' + i;
            currentBook.Description__c = 'Book Description' + i;
            currentBook.ISBN__c = '555333' + i;
            currentBook.Language__c = 'English';
            currentBook.Categories__c = 'Fantasy';
            currentBook.Publisher__c = publisherId;
            currentBook.Publish_Date__c = Date.newInstance(2022, 1, 1);
            booksForTest.add(currentBook);
        }
        return booksForTest;
    }
}