force-app/main/default/objects/Book__c/Book__c.object-meta.xml
<CustomObject>
    <label>Book</label>
    <nameField>
        <label>Book Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Books</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Book_Review__c/Book_Review__c.object-meta.xml
<CustomObject>
    <label>Book Review</label>
    <nameField>
        <label>Subject</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Book Reviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Book_Review__c/fields/Book__c.field-meta.xml
<CustomField>
    <fullName>Book__c</fullName>
    <description>Master - Detail relationship with associated Book</description>
    <inlineHelpText>Master - Detail relationship with associated Book</inlineHelpText>
    <label>Book</label>
    <referenceTo>Book__c</referenceTo>
    <relationshipLabel>Book Reviews</relationshipLabel>
    <relationshipName>Book_Reviews</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/Repository/Selector/BookReviewSelector.cls
/*
* Class used for selecting book reviews from database
*/
public with sharing class BookReviewSelector implements CustomObject {
    /*
    * Method used for retrieving all book reviews from the database
    */
    public List<Book_Review__c> getList() {
        return [
            SELECT
                Id,
                Book__c,
                CreatedById
            FROM Book_Review__c
        ];
    }
}