force-app/main/default/objects/Book__c/Book__c.object-meta.xml
<CustomObject>
    <label>Book</label>
    <nameField>
        <label>Book Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Books</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Book_Purchase__c/Book_Purchase__c.object-meta.xml
<CustomObject>
    <label>Book Purchase</label>
    <nameField>
        <displayFormat>BP-{0000}</displayFormat>
        <label>Book Purchase Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Book Purchases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Book_Purchase__c/fields/Book__c.field-meta.xml
<CustomField>
    <fullName>Book__c</fullName>
    <label>Book</label>
    <referenceTo>Book__c</referenceTo>
    <relationshipLabel>Book Purchases</relationshipLabel>
    <relationshipName>Book_Purchases</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/Repository/Selector/BookPurchaseSelector.cls
/*
 * This class is used for retrieving Book_Purchase__c records from database
 */
public with sharing class BookPurchaseSelector implements CustomObject{
    /*
     * @param bookIds - set of book Ids that were bought
     */
    public List<Book_Purchase__c> getList(Set<Id> bookIds) {
        return [
            SELECT
                Id,
                Book__c,
                CreatedById
            FROM Book_Purchase__c
        ];
    }
}