force-app/main/default/objects/Book__c/Book__c.object-meta.xml
<CustomObject>
    <label>Book</label>
    <nameField>
        <label>Book Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Books</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Book__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Price</label>
    <precision>17</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Book_Reservation__c/Book_Reservation__c.object-meta.xml
<CustomObject>
    <label>Book Reservation</label>
    <nameField>
        <displayFormat>RES-{0000}</displayFormat>
        <label>Book Reservation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Book Reservations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Book_Reservation__c/fields/Book__c.field-meta.xml
<CustomField>
    <fullName>Book__c</fullName>
    <label>Book</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>You must select a Paper Book!</errorMessage>
        <filterItems>
            <field>Book__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Paper Book</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Book__c</referenceTo>
    <relationshipLabel>Book Reservations</relationshipLabel>
    <relationshipName>Book_Reservations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Book_Reservation__c/fields/Bookstore__c.field-meta.xml
<CustomField>
    <fullName>Bookstore__c</fullName>
    <label>Bookstore</label>
    <referenceTo>Bookstore__c</referenceTo>
    <relationshipLabel>Book Reservations</relationshipLabel>
    <relationshipName>Book_Reservations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Bookstore__c/Bookstore__c.object-meta.xml
<CustomObject>
    <label>Bookstore</label>
    <nameField>
        <label>Bookstore Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookstores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Bookstore_Book__c/Bookstore_Book__c.object-meta.xml
<CustomObject>
    <label>Bookstore_Book</label>
    <nameField>
        <label>Bookstore_Book Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookstore_Books</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bookstore_Book__c/fields/Book__c.field-meta.xml
<CustomField>
    <fullName>Book__c</fullName>
    <label>Book</label>
    <referenceTo>Book__c</referenceTo>
    <relationshipLabel>Bookstore Books</relationshipLabel>
    <relationshipName>Bookstore_Books</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Bookstore_Book__c/fields/Bookstore__c.field-meta.xml
<CustomField>
    <fullName>Bookstore__c</fullName>
    <label>Bookstore</label>
    <referenceTo>Bookstore__c</referenceTo>
    <relationshipLabel>Bookstore Books</relationshipLabel>
    <relationshipName>Bookstore_Books</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Bookstore_Book__c/fields/Number_Of_Active_Reservations__c.field-meta.xml
<CustomField>
    <fullName>Number_Of_Active_Reservations__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Number Of Active Reservations</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Bookstore_Book__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <description>Number of copies of a single book title.</description>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/Service/BookReservationValidationService.cls
/**
 * Class that contains a method to validate if selected Bookstore has the appropriate
 * amound of selected books
 * 
 * @see BookReservationTriggerHandler.cls
 */
public with sharing class BookReservationValidationService implements CustomObject {
    /**
     * Method which checks if Bookstore contains the appropriate amount of selected Books
     * when reservations are being created or updated
     * 
     * @param oldBookReservations list of BookReservation records with old values (this is null if the record is being created)
     * @param newBookReservation list of BookReservation records with new values
     */
    public void validateSelectedBook (List<Book_Reservation__c> oldBookReservations, List<Book_Reservation__c> newBookReservations) {
        Set<Id> bookstoreIds = new Set<Id>();
        Set<Id> bookIds = new Set<Id>();

        for (Book_Reservation__c bookReservation : newBookReservations) {
            bookstoreIds.add(bookReservation.Bookstore__c);
            bookIds.add(bookReservation.Book__c);
        }

        BookstoreBookSelector bookstoreBookSelector = (BookstoreBookSelector) new ObjectFactory().createObject(BookstoreBookSelector.class);
        List<Bookstore_Book__c> bookstoreBooks = bookstoreBookSelector.getListByBookstoreAndBookIds(bookstoreIds, bookIds);

        List<Bookstore_Book__c> bookstoreBooksToUpdate = new List<Bookstore_Book__c>();

        for (Book_Reservation__c bookReservation : newBookReservations) {
            Boolean noBookstoreBooks = true;
            for (Bookstore_Book__c bookstoreBook : bookstoreBooks) {
                if (bookReservation.Bookstore__c == bookstoreBook.Bookstore__c && bookReservation.Book__c == bookstoreBook.Book__c) {
                    noBookstoreBooks = false;
                    if (oldBookReservations != null) {
                        /*If the reservation is being updated, we need to find the old reservation quantity to take it into account
                        because BookstoreBook Quantity is not reduced yet when the reservation is active */
                        for (Book_Reservation__c oldReservation : oldBookReservations) {
                            if (bookReservation.Id == oldReservation.Id) {
                                Integer availableBooks = (Integer) bookstoreBook.Quantity__c - (Integer) bookstoreBook.Number_Of_Active_Reservations__c + (Integer) oldReservation.Quantity__c;
                        
                                if (bookReservation.Quantity__c > availableBooks) {
                                    bookReservation.addError('There are no enough books! You can choose up to ' + availableBooks + '.');
                                } else {
                                    bookstoreBook.Number_Of_Active_Reservations__c = bookstoreBook.Number_Of_Active_Reservations__c - oldReservation.Quantity__c + bookReservation.Quantity__c;
                                    bookstoreBooksToUpdate.add(bookstoreBook);
                                    //Send confirmation email
                                    SendReservationEmailConfirmationService confirmationEmail = (SendReservationEmailConfirmationService) new ObjectFactory().createObject(SendReservationEmailConfirmationService.class);
                                    Decimal totalPrice = bookstoreBook.Book__r.Price__c * (Integer) bookReservation.Quantity__c;
                                    bookReservation.Price__c = totalPrice;
                                    confirmationEmail.sendMail(UserInfo.getUserEmail(), bookstoreBook.Book__r.Name, (Integer) bookReservation.Quantity__c, totalPrice);
                                }
                            }
                        }

                    } else {
                        Integer availableBooks = (Integer) bookstoreBook.Quantity__c - (Integer) bookstoreBook.Number_Of_Active_Reservations__c;
                        
                        if (bookReservation.Quantity__c > availableBooks) {
                            bookReservation.addError('There are no enough books! You can choose up to ' + availableBooks + '.');
                        } else {
                            bookstoreBook.Number_Of_Active_Reservations__c += bookReservation.Quantity__c;
                            bookstoreBooksToUpdate.add(bookstoreBook);
                            //Send confirmation email
                            SendReservationEmailConfirmationService confirmationEmail = (SendReservationEmailConfirmationService) new ObjectFactory().createObject(SendReservationEmailConfirmationService.class);
                            Decimal totalPrice = bookstoreBook.Book__r.Price__c * (Integer) bookReservation.Quantity__c;
                            bookReservation.Price__c = totalPrice;
                            confirmationEmail.sendMail(UserInfo.getUserEmail(), bookstoreBook.Book__r.Name, (Integer) bookReservation.Quantity__c, totalPrice);
                        }
                    }
                }
            }
            if (noBookstoreBooks) {
                bookReservation.addError('There is no selected Book in selected Bookstore!');
            }
        }

        if (!bookstoreBooksToUpdate.isEmpty()) {
            Database.update(bookstoreBooksToUpdate, false);
        }
    }
}