force-app/main/default/objects/Book__c/Book__c.object-meta.xml
<CustomObject>
    <label>Book</label>
    <nameField>
        <label>Book Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Books</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Book__c/fields/Publisher__c.field-meta.xml
<CustomField>
    <fullName>Publisher__c</fullName>
    <label>Publisher</label>
    <referenceTo>Publisher__c</referenceTo>
    <relationshipLabel>Books</relationshipLabel>
    <relationshipName>Books</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Bookstore__c/Bookstore__c.object-meta.xml
<CustomObject>
    <label>Bookstore</label>
    <nameField>
        <label>Bookstore Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookstores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Bookstore_Book__c/Bookstore_Book__c.object-meta.xml
<CustomObject>
    <label>Bookstore_Book</label>
    <nameField>
        <label>Bookstore_Book Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookstore_Books</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bookstore_Book__c/fields/Book__c.field-meta.xml
<CustomField>
    <fullName>Book__c</fullName>
    <label>Book</label>
    <referenceTo>Book__c</referenceTo>
    <relationshipLabel>Bookstore Books</relationshipLabel>
    <relationshipName>Bookstore_Books</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Bookstore_Book__c/fields/Bookstore__c.field-meta.xml
<CustomField>
    <fullName>Bookstore__c</fullName>
    <label>Bookstore</label>
    <referenceTo>Bookstore__c</referenceTo>
    <relationshipLabel>Bookstore Books</relationshipLabel>
    <relationshipName>Bookstore_Books</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Bookstore_Publisher__c/Bookstore_Publisher__c.object-meta.xml
<CustomObject>
    <label>Bookstore_Publisher</label>
    <nameField>
        <displayFormat>BP-{0000}</displayFormat>
        <label>Bookstore Publisher Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookstore Publishers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bookstore_Publisher__c/fields/Bookstore__c.field-meta.xml
<CustomField>
    <fullName>Bookstore__c</fullName>
    <label>Bookstore</label>
    <referenceTo>Bookstore__c</referenceTo>
    <relationshipName>Bookstore_Publishers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Bookstore_Publisher__c/fields/Publisher__c.field-meta.xml
<CustomField>
    <fullName>Publisher__c</fullName>
    <label>Publisher</label>
    <referenceTo>Publisher__c</referenceTo>
    <relationshipName>Bookstore_Publishers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Publisher__c/Publisher__c.object-meta.xml
<CustomObject>
    <label>Publisher</label>
    <nameField>
        <label>Publisher Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Publishers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/Service/BookstoreBookValidationService.cls
/*
* Validates if the Book that is being added to the bookstore(Via creating Bookstore_Book__c object) has the same publisher
* as the bookstore that it is being added too
*/
public with sharing class BookstoreBookValidationService implements CustomObject {
    /*
    * @param newBookstoreBooks - Books added to the bookstore
    */
    public void validatePublisher(List<Bookstore_Book__c> newBookstoreBooks) {
        //Set of book ids corresponding to added bookstoreBooks
        Set<Id> addedBookIds = new Set<Id>();
        //List that holds pairs of publisher and bookstore Ids corresponding to the Bookstore_Book__c object
        List<List<Id>> publisherAndBookstoreIds = new List<List<Id>>();
        //Loop through all new records and put all book ids into a set
        for(Bookstore_Book__c bookstoreBook : newBookstoreBooks) {
            addedBookIds.add(bookstoreBook.Book__c);
        }
        //Create book selector object and get all books that were added
        BookSelector bookSelector = (BookSelector) new ObjectFactory().createObject(BookSelector.class);
        Map<Id, Book__c> correspondingBooks = bookSelector.getBooksBySetOfIds(addedBookIds);
        //Create pairs of publishers and bookstores
        for(Bookstore_Book__c bookstoreBook: newBookstoreBooks) {
            List<Id> currentList = new List<Id>();
            currentList.add(correspondingBooks.get(bookstoreBook.Book__c).Publisher__c);
            currentList.add(bookstoreBook.Bookstore__c);
            publisherAndBookstoreIds.add(currentList);
        }
        //Get all Bookstore_Publisher__c object that correspond to the list of pairs
        BookstorePublisherSelector bkstorePubSelector = (BookstorePublisherSelector) new ObjectFactory()
        .createObject(BookstorePublisherSelector.class);
        List<Bookstore_Publisher__c> bookstorePublishers = bkstorePubSelector
        .getBookstorePublishersWithPublisherAndBookstoreId(publisherAndBookstoreIds);
        //Check which Bookstore_Book__c objects are valid and for the rest add errors.
        for(Bookstore_Book__c bookstoreBook: newBookstoreBooks) {
            Boolean isValid = false;
            for(Bookstore_Publisher__c bkstorePub : bookstorePublishers) {
                Id publisherId = correspondingBooks.get(bookstoreBook.Book__c).Publisher__c;
                if(bookstoreBook.Bookstore__c == bkstorePub.Bookstore__c && bkstorePub.Publisher__c == publisherId ) {
                    isValid = true;
                    break;
                }   
            }
            if(!isValid) {
                bookstoreBook.addError('Book and bookstore must work with the same publisher!');
            }   
        }
    }
}