force-app/main/default/objects/Book__c/Book__c.object-meta.xml
<CustomObject>
    <label>Book</label>
    <nameField>
        <label>Book Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Books</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Book__c/fields/Publisher__c.field-meta.xml
<CustomField>
    <fullName>Publisher__c</fullName>
    <label>Publisher</label>
    <referenceTo>Publisher__c</referenceTo>
    <relationshipLabel>Books</relationshipLabel>
    <relationshipName>Books</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Bookstore__c/Bookstore__c.object-meta.xml
<CustomObject>
    <label>Bookstore</label>
    <nameField>
        <label>Bookstore Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookstores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Bookstore_Book__c/Bookstore_Book__c.object-meta.xml
<CustomObject>
    <label>Bookstore_Book</label>
    <nameField>
        <label>Bookstore_Book Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookstore_Books</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bookstore_Book__c/fields/Book__c.field-meta.xml
<CustomField>
    <fullName>Book__c</fullName>
    <label>Book</label>
    <referenceTo>Book__c</referenceTo>
    <relationshipLabel>Bookstore Books</relationshipLabel>
    <relationshipName>Bookstore_Books</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Bookstore_Book__c/fields/Bookstore__c.field-meta.xml
<CustomField>
    <fullName>Bookstore__c</fullName>
    <label>Bookstore</label>
    <referenceTo>Bookstore__c</referenceTo>
    <relationshipLabel>Bookstore Books</relationshipLabel>
    <relationshipName>Bookstore_Books</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Bookstore_Publisher__c/Bookstore_Publisher__c.object-meta.xml
<CustomObject>
    <label>Bookstore_Publisher</label>
    <nameField>
        <displayFormat>BP-{0000}</displayFormat>
        <label>Bookstore Publisher Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookstore Publishers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bookstore_Publisher__c/fields/Bookstore__c.field-meta.xml
<CustomField>
    <fullName>Bookstore__c</fullName>
    <label>Bookstore</label>
    <referenceTo>Bookstore__c</referenceTo>
    <relationshipName>Bookstore_Publishers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Bookstore_Publisher__c/fields/Publisher__c.field-meta.xml
<CustomField>
    <fullName>Publisher__c</fullName>
    <label>Publisher</label>
    <referenceTo>Publisher__c</referenceTo>
    <relationshipName>Bookstore_Publishers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Publisher__c/Publisher__c.object-meta.xml
<CustomObject>
    <label>Publisher</label>
    <nameField>
        <label>Publisher Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Publishers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/test/default/classes/unit/TestFactoryTest.cls
@isTest
public with sharing class TestFactoryTest {
    @isTest
    public static void createPublishers_willCreateFivePublishers() {
        Test.startTest();
        List<Publisher__c> publishersForTest = new TestFactory().createPublishers(5);
        Test.stopTest();
        System.assertEquals(5, publishersForTest.size());
    }
     /*
    * Id used is dummy 18 character Id used for creating the records without inserting
    */
    @isTest
    public static void createBooks_willCreateFiveBooks() {
        List<Publisher__c> publishersForTest = new TestFactory().createPublishers(1);
        insert publishersForTest;
        Test.startTest();
        List<Book__c> booksForTest = new TestFactory().createBooks(5, publishersForTest[0].Id);
        Test.stopTest();
        System.assertEquals(5, booksForTest.size());
    }

    @isTest
    public static void createBookstores_willCreateFiveBookstores() {
        Test.startTest();
        List<Bookstore__c> bookstoresForTest = new TestFactory().createBookstores(5);
        Test.stopTest();
        System.assertEquals(5, bookstoresForTest.size());
    }
    /*
    * Id used is dummy 18 character Id used for creating the records without inserting
    */
    @isTest
    public static void createBookstorePublishers_willCreateFiveBookstorePublishers() {
        List<Publisher__c> publishersForTest = new TestFactory().createPublishers(1);
        insert publishersForTest;
        List<Bookstore__c> bookstoresForTest = new TestFactory().createBookstores(1);
        insert bookstoresForTest;
        Test.startTest();
        List<Bookstore_Publisher__c> bookStorePublishers = new TestFactory().createBookstorePublishers(5, publishersForTest[0].Id, bookstoresForTest[0].Id);
        Test.stopTest();
        System.assertEquals(5, bookStorePublishers.size());
    }
    /*
    * Ids used here are dummy 18 character ids just used for creating the objects without insertion
    */
    @isTest
    public static void createBookstoreBooks_willCreatefiveBooks() {
        List<Publisher__c> publishersForTest = new TestFactory().createPublishers(1);
        insert publishersForTest;
        List<Book__c> booksForTest = new TestFactory().createBooks(1, publishersForTest[0].Id);
        insert booksForTest;
        List<Bookstore__c> bookstoresForTest = new TestFactory().createBookstores(1);
        Test.startTest();
        List<Bookstore_Book__c> bookbooksFortest = new TestFactory().createBookstoreBooks(5, booksForTest[0].Id, bookstoresForTest[0].Id);
        Test.stopTest();
        System.assertEquals(5,bookbooksFortest.size());
    }
}